/* eslint-disable no-console */
/**
 * Category attribute definitions and product-specific values for the
 * product-page test matrix.
 *
 *   cd modules/marketplace/backend
 *   npx ts-node --transpile-only -r tsconfig-paths/register scripts/seed-product-attributes.ts
 *
 * Idempotent: definitions upsert on (category, slug); values upsert on
 * (product, attribute). Every value is run through the same validator the
 * seller write path uses, so the seed cannot store what a seller could not.
 * Connects through the module's own DataSource (the `marketplace_user` role).
 *
 * Twelve real, approved catalogue products, one or two per category the
 * brief names — smartphone, laptop, TV, refrigerator, washing machine, air
 * conditioner, men's and women's clothing, running shoes, makeup, office
 * furniture, earbuds — so the specification set demonstrably changes per
 * category rather than showing one template everywhere.
 */
import 'dotenv/config';
import { In } from 'typeorm';
import { MarketplaceDataSource } from '../data-source';
import { Category } from '../src/entities/category.entity';
import { Product } from '../src/entities/product.entity';
import { ProductAttribute, type AttributeOption } from '../src/entities/product-attribute.entity';
import { ProductAttributeValue } from '../src/entities/product-attribute-value.entity';
import { AttributeValuesService } from '../src/catalog/attribute-values.service';

type Def = {
  slug: string;
  name: string;
  type: string;
  group: string;
  unit?: string;
  highlight?: boolean;
  required?: boolean;
  min?: number;
  max?: number;
  options?: string[];
  sortOrder?: number;
};

const opts = (labels: string[]): AttributeOption[] =>
  labels.map((label) => ({ label, value: label.toLowerCase().replace(/[^a-z0-9]+/g, '-') }));

const STARS = ['1 Star', '2 Star', '3 Star', '4 Star', '5 Star'];
const WARRANTY: Def = {
  slug: 'warranty',
  name: 'Warranty',
  type: 'TEXT',
  group: 'Warranty',
  required: true,
  sortOrder: 900,
};
const ORIGIN: Def = {
  slug: 'country-of-origin',
  name: 'Country of origin',
  type: 'TEXT',
  group: 'General',
  sortOrder: 890,
};

/** Definitions per category slug (leaf or parent; children inherit). */
const DEFINITIONS: Record<string, Def[]> = {
  smartphones: [
    { slug: 'model', name: 'Model', type: 'TEXT', group: 'General', required: true, sortOrder: 1 },
    {
      slug: 'operating-system',
      name: 'Operating system',
      type: 'SELECT',
      group: 'Performance',
      options: ['iOS', 'Android', 'HarmonyOS'],
      highlight: true,
      required: true,
      sortOrder: 10,
    },
    {
      slug: 'processor',
      name: 'Processor',
      type: 'TEXT',
      group: 'Performance',
      highlight: true,
      required: true,
      sortOrder: 11,
    },
    {
      slug: 'ram',
      name: 'RAM',
      type: 'NUMBER',
      unit: 'GB',
      group: 'Performance',
      highlight: true,
      required: true,
      min: 1,
      max: 64,
      sortOrder: 12,
    },
    {
      slug: 'display-size',
      name: 'Display size',
      type: 'NUMBER',
      unit: 'inch',
      group: 'Display',
      highlight: true,
      required: true,
      min: 3,
      max: 15,
      sortOrder: 20,
    },
    {
      slug: 'display-type',
      name: 'Display type',
      type: 'SELECT',
      group: 'Display',
      options: ['OLED', 'LTPO OLED', 'AMOLED', 'LCD'],
      sortOrder: 21,
    },
    { slug: 'resolution', name: 'Resolution', type: 'TEXT', group: 'Display', sortOrder: 22 },
    {
      slug: 'refresh-rate',
      name: 'Refresh rate',
      type: 'NUMBER',
      unit: 'Hz',
      group: 'Display',
      min: 60,
      max: 240,
      sortOrder: 23,
    },
    {
      slug: 'rear-camera',
      name: 'Rear camera',
      type: 'TEXT',
      group: 'Camera',
      highlight: true,
      sortOrder: 30,
    },
    { slug: 'front-camera', name: 'Front camera', type: 'TEXT', group: 'Camera', sortOrder: 31 },
    {
      slug: 'battery-capacity',
      name: 'Battery capacity',
      type: 'NUMBER',
      unit: 'mAh',
      group: 'Battery',
      highlight: true,
      min: 500,
      max: 20000,
      sortOrder: 40,
    },
    { slug: 'charging', name: 'Charging', type: 'TEXT', group: 'Battery', sortOrder: 41 },
    {
      slug: 'sim-type',
      name: 'SIM',
      type: 'SELECT',
      group: 'Connectivity',
      options: ['Single SIM', 'Dual SIM', 'Dual SIM + eSIM'],
      sortOrder: 50,
    },
    {
      slug: '5g',
      name: '5G',
      type: 'BOOLEAN',
      group: 'Connectivity',
      highlight: true,
      sortOrder: 51,
    },
    { slug: 'nfc', name: 'NFC', type: 'BOOLEAN', group: 'Connectivity', sortOrder: 52 },
    {
      slug: 'usb-type',
      name: 'USB',
      type: 'SELECT',
      group: 'Connectivity',
      options: ['USB-C', 'Lightning', 'Micro-USB'],
      sortOrder: 53,
    },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'g',
      group: 'Dimensions',
      min: 50,
      max: 1000,
      sortOrder: 60,
    },
    WARRANTY,
  ],
  laptops: [
    {
      slug: 'processor',
      name: 'Processor',
      type: 'TEXT',
      group: 'Performance',
      highlight: true,
      required: true,
      sortOrder: 10,
    },
    {
      slug: 'processor-generation',
      name: 'Processor generation',
      type: 'TEXT',
      group: 'Performance',
      sortOrder: 11,
    },
    {
      slug: 'ram',
      name: 'RAM',
      type: 'NUMBER',
      unit: 'GB',
      group: 'Performance',
      highlight: true,
      required: true,
      min: 2,
      max: 128,
      sortOrder: 12,
    },
    {
      slug: 'ram-type',
      name: 'RAM type',
      type: 'SELECT',
      group: 'Performance',
      options: ['DDR4', 'DDR5', 'LPDDR5'],
      sortOrder: 13,
    },
    {
      slug: 'storage-type',
      name: 'Storage type',
      type: 'SELECT',
      group: 'Storage',
      options: ['SSD', 'HDD', 'SSD + HDD'],
      sortOrder: 20,
    },
    {
      slug: 'storage-capacity',
      name: 'Storage capacity',
      type: 'NUMBER',
      unit: 'GB',
      group: 'Storage',
      highlight: true,
      required: true,
      min: 32,
      max: 8192,
      sortOrder: 21,
    },
    {
      slug: 'display-size',
      name: 'Display size',
      type: 'NUMBER',
      unit: 'inch',
      group: 'Display',
      highlight: true,
      required: true,
      min: 10,
      max: 20,
      sortOrder: 30,
    },
    { slug: 'resolution', name: 'Resolution', type: 'TEXT', group: 'Display', sortOrder: 31 },
    {
      slug: 'refresh-rate',
      name: 'Refresh rate',
      type: 'NUMBER',
      unit: 'Hz',
      group: 'Display',
      min: 60,
      max: 360,
      sortOrder: 32,
    },
    { slug: 'graphics', name: 'Graphics', type: 'TEXT', group: 'Performance', sortOrder: 14 },
    {
      slug: 'operating-system',
      name: 'Operating system',
      type: 'SELECT',
      group: 'General',
      options: ['Windows 11', 'macOS', 'ChromeOS', 'Linux'],
      highlight: true,
      sortOrder: 2,
    },
    { slug: 'battery', name: 'Battery', type: 'TEXT', group: 'Battery', sortOrder: 40 },
    {
      slug: 'ports',
      name: 'Ports',
      type: 'MULTI_SELECT',
      group: 'Connectivity',
      options: ['USB-C', 'USB-A', 'HDMI', 'Thunderbolt 4', 'SD card', 'Audio jack', 'Ethernet'],
      sortOrder: 50,
    },
    { slug: 'wifi', name: 'Wi-Fi', type: 'TEXT', group: 'Connectivity', sortOrder: 51 },
    { slug: 'bluetooth', name: 'Bluetooth', type: 'TEXT', group: 'Connectivity', sortOrder: 52 },
    { slug: 'webcam', name: 'Webcam', type: 'TEXT', group: 'General', sortOrder: 3 },
    { slug: 'keyboard', name: 'Keyboard', type: 'TEXT', group: 'General', sortOrder: 4 },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'kg',
      group: 'Dimensions',
      min: 0.3,
      max: 6,
      sortOrder: 60,
    },
    WARRANTY,
  ],
  'headphones-and-earbuds': [
    {
      slug: 'form-factor',
      name: 'Form factor',
      type: 'SELECT',
      group: 'General',
      options: ['In-ear', 'On-ear', 'Over-ear'],
      highlight: true,
      required: true,
      sortOrder: 1,
    },
    {
      slug: 'noise-cancellation',
      name: 'Active noise cancellation',
      type: 'BOOLEAN',
      group: 'Audio',
      highlight: true,
      sortOrder: 10,
    },
    {
      slug: 'driver-size',
      name: 'Driver size',
      type: 'NUMBER',
      unit: 'mm',
      group: 'Audio',
      min: 3,
      max: 60,
      sortOrder: 11,
    },
    {
      slug: 'battery-life',
      name: 'Battery life',
      type: 'NUMBER',
      unit: 'hours',
      group: 'Battery',
      highlight: true,
      min: 1,
      max: 200,
      sortOrder: 20,
    },
    { slug: 'bluetooth', name: 'Bluetooth', type: 'TEXT', group: 'Connectivity', sortOrder: 30 },
    { slug: 'microphone', name: 'Microphone', type: 'BOOLEAN', group: 'Audio', sortOrder: 12 },
    {
      slug: 'water-resistance',
      name: 'Water resistance',
      type: 'TEXT',
      group: 'General',
      sortOrder: 2,
    },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'g',
      group: 'Dimensions',
      min: 1,
      max: 1000,
      sortOrder: 60,
    },
    WARRANTY,
  ],
  tvs: [
    {
      slug: 'screen-size',
      name: 'Screen size',
      type: 'NUMBER',
      unit: 'inch',
      group: 'Display',
      highlight: true,
      required: true,
      min: 20,
      max: 120,
      sortOrder: 1,
    },
    {
      slug: 'resolution',
      name: 'Resolution',
      type: 'SELECT',
      group: 'Display',
      options: ['HD', 'Full HD', '4K', '8K'],
      highlight: true,
      required: true,
      sortOrder: 2,
    },
    {
      slug: 'panel-type',
      name: 'Panel',
      type: 'SELECT',
      group: 'Display',
      options: ['LED', 'QLED', 'OLED', 'Mini LED'],
      highlight: true,
      sortOrder: 3,
    },
    {
      slug: 'refresh-rate',
      name: 'Refresh rate',
      type: 'NUMBER',
      unit: 'Hz',
      group: 'Display',
      min: 50,
      max: 240,
      sortOrder: 4,
    },
    { slug: 'hdr', name: 'HDR formats', type: 'TEXT', group: 'Display', sortOrder: 5 },
    {
      slug: 'smart-platform',
      name: 'Smart platform',
      type: 'TEXT',
      group: 'Smart features',
      sortOrder: 10,
    },
    {
      slug: 'hdmi-ports',
      name: 'HDMI ports',
      type: 'NUMBER',
      group: 'Connectivity',
      min: 0,
      max: 8,
      sortOrder: 20,
    },
    {
      slug: 'sound-output',
      name: 'Sound output',
      type: 'NUMBER',
      unit: 'W',
      group: 'Audio',
      min: 1,
      max: 500,
      sortOrder: 30,
    },
    {
      slug: 'wall-mount',
      name: 'Wall mountable',
      type: 'BOOLEAN',
      group: 'General',
      sortOrder: 40,
    },
    WARRANTY,
  ],
  refrigerators: [
    {
      slug: 'capacity',
      name: 'Capacity',
      type: 'NUMBER',
      unit: 'L',
      group: 'General',
      highlight: true,
      required: true,
      min: 20,
      max: 1500,
      sortOrder: 1,
    },
    {
      slug: 'refrigerator-type',
      name: 'Type',
      type: 'SELECT',
      group: 'General',
      options: ['Single door', 'Double door', 'Side-by-side', 'Bottom freezer'],
      highlight: true,
      required: true,
      sortOrder: 2,
    },
    {
      slug: 'number-of-doors',
      name: 'Doors',
      type: 'NUMBER',
      group: 'General',
      min: 1,
      max: 6,
      sortOrder: 3,
    },
    {
      slug: 'energy-rating',
      name: 'Energy rating',
      type: 'SELECT',
      group: 'Efficiency',
      options: STARS,
      highlight: true,
      sortOrder: 10,
    },
    {
      slug: 'compressor-type',
      name: 'Compressor',
      type: 'SELECT',
      group: 'Efficiency',
      options: ['Inverter', 'Standard'],
      highlight: true,
      sortOrder: 11,
    },
    {
      slug: 'cooling-technology',
      name: 'Cooling technology',
      type: 'TEXT',
      group: 'Cooling',
      sortOrder: 20,
    },
    {
      slug: 'defrost-system',
      name: 'Defrost',
      type: 'SELECT',
      group: 'Cooling',
      options: ['Frost free', 'Direct cool'],
      sortOrder: 21,
    },
    {
      slug: 'dimensions',
      name: 'Dimensions (H × W × D)',
      type: 'TEXT',
      group: 'Dimensions',
      sortOrder: 60,
    },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'kg',
      group: 'Dimensions',
      min: 5,
      max: 400,
      sortOrder: 61,
    },
    WARRANTY,
  ],
  'washing-machines': [
    {
      slug: 'capacity',
      name: 'Capacity',
      type: 'NUMBER',
      unit: 'kg',
      group: 'General',
      highlight: true,
      required: true,
      min: 3,
      max: 30,
      sortOrder: 1,
    },
    {
      slug: 'washer-type',
      name: 'Type',
      type: 'SELECT',
      group: 'General',
      options: ['Front load', 'Top load', 'Semi-automatic'],
      highlight: true,
      required: true,
      sortOrder: 2,
    },
    {
      slug: 'spin-speed',
      name: 'Max spin speed',
      type: 'NUMBER',
      unit: 'rpm',
      group: 'Performance',
      min: 300,
      max: 2000,
      sortOrder: 10,
    },
    {
      slug: 'energy-rating',
      name: 'Energy rating',
      type: 'SELECT',
      group: 'Efficiency',
      options: STARS,
      highlight: true,
      sortOrder: 20,
    },
    {
      slug: 'inverter-motor',
      name: 'Inverter motor',
      type: 'BOOLEAN',
      group: 'Efficiency',
      highlight: true,
      sortOrder: 21,
    },
    {
      slug: 'wash-programs',
      name: 'Wash programs',
      type: 'NUMBER',
      group: 'Performance',
      min: 1,
      max: 60,
      sortOrder: 11,
    },
    {
      slug: 'dimensions',
      name: 'Dimensions (H × W × D)',
      type: 'TEXT',
      group: 'Dimensions',
      sortOrder: 60,
    },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'kg',
      group: 'Dimensions',
      min: 10,
      max: 200,
      sortOrder: 61,
    },
    WARRANTY,
  ],
  'air-conditioners': [
    {
      slug: 'capacity',
      name: 'Capacity',
      type: 'NUMBER',
      unit: 'ton',
      group: 'General',
      highlight: true,
      required: true,
      min: 0.5,
      max: 5,
      sortOrder: 1,
    },
    {
      slug: 'ac-type',
      name: 'Type',
      type: 'SELECT',
      group: 'General',
      options: ['Split', 'Window', 'Cassette', 'Portable'],
      highlight: true,
      required: true,
      sortOrder: 2,
    },
    {
      slug: 'energy-rating',
      name: 'Energy rating',
      type: 'SELECT',
      group: 'Efficiency',
      options: STARS,
      highlight: true,
      sortOrder: 10,
    },
    {
      slug: 'inverter',
      name: 'Inverter compressor',
      type: 'BOOLEAN',
      group: 'Efficiency',
      highlight: true,
      sortOrder: 11,
    },
    {
      slug: 'cooling-capacity',
      name: 'Cooling capacity',
      type: 'NUMBER',
      unit: 'W',
      group: 'Performance',
      min: 1000,
      max: 20000,
      sortOrder: 20,
    },
    { slug: 'refrigerant', name: 'Refrigerant', type: 'TEXT', group: 'Performance', sortOrder: 21 },
    {
      slug: 'noise-level',
      name: 'Noise level',
      type: 'NUMBER',
      unit: 'dB',
      group: 'Performance',
      min: 10,
      max: 80,
      sortOrder: 22,
    },
    WARRANTY,
  ],
  fashion: [
    {
      slug: 'gender',
      name: 'Gender',
      type: 'SELECT',
      group: 'General',
      options: ['Men', 'Women', 'Unisex', 'Kids'],
      required: true,
      sortOrder: 1,
    },
    {
      slug: 'material',
      name: 'Material',
      type: 'TEXT',
      group: 'Fabric',
      highlight: true,
      required: true,
      sortOrder: 10,
    },
    { slug: 'fabric', name: 'Fabric', type: 'TEXT', group: 'Fabric', sortOrder: 11 },
    {
      slug: 'fit',
      name: 'Fit',
      type: 'SELECT',
      group: 'Style',
      options: ['Regular', 'Slim', 'Relaxed', 'Oversized'],
      highlight: true,
      sortOrder: 20,
    },
    {
      slug: 'pattern',
      name: 'Pattern',
      type: 'SELECT',
      group: 'Style',
      options: ['Solid', 'Striped', 'Printed', 'Checked'],
      sortOrder: 21,
    },
    {
      slug: 'sleeve-type',
      name: 'Sleeve',
      type: 'SELECT',
      group: 'Style',
      options: ['Short sleeve', 'Long sleeve', 'Sleeveless'],
      sortOrder: 22,
    },
    {
      slug: 'neck-type',
      name: 'Neck',
      type: 'SELECT',
      group: 'Style',
      options: ['Round neck', 'V-neck', 'Crew neck', 'Polo'],
      sortOrder: 23,
    },
    { slug: 'care-instructions', name: 'Care', type: 'TEXT', group: 'Care', sortOrder: 30 },
    ORIGIN,
  ],
  'running-shoes': [
    {
      slug: 'shoe-type',
      name: 'Type',
      type: 'SELECT',
      group: 'General',
      options: ['Road running', 'Trail running', 'Racing', 'Walking'],
      highlight: true,
      required: true,
      sortOrder: 1,
    },
    { slug: 'upper-material', name: 'Upper', type: 'TEXT', group: 'Construction', sortOrder: 10 },
    { slug: 'sole-material', name: 'Outsole', type: 'TEXT', group: 'Construction', sortOrder: 11 },
    {
      slug: 'cushioning',
      name: 'Cushioning',
      type: 'TEXT',
      group: 'Construction',
      highlight: true,
      sortOrder: 12,
    },
    {
      slug: 'heel-drop',
      name: 'Heel-to-toe drop',
      type: 'NUMBER',
      unit: 'mm',
      group: 'Construction',
      min: 0,
      max: 20,
      sortOrder: 13,
    },
    {
      slug: 'weight',
      name: 'Weight (per shoe)',
      type: 'NUMBER',
      unit: 'g',
      group: 'Construction',
      highlight: true,
      min: 50,
      max: 800,
      sortOrder: 14,
    },
    {
      slug: 'closure',
      name: 'Closure',
      type: 'SELECT',
      group: 'General',
      options: ['Lace-up', 'Slip-on', 'Velcro'],
      sortOrder: 2,
    },
    ORIGIN,
  ],
  makeup: [
    {
      slug: 'form',
      name: 'Form',
      type: 'SELECT',
      group: 'General',
      options: ['Liquid', 'Cream', 'Powder', 'Stick'],
      required: true,
      sortOrder: 1,
    },
    {
      slug: 'skin-type',
      name: 'Suitable for',
      type: 'MULTI_SELECT',
      group: 'Suitability',
      options: ['Normal', 'Dry', 'Oily', 'Combination', 'Sensitive'],
      highlight: true,
      sortOrder: 10,
    },
    {
      slug: 'coverage',
      name: 'Coverage',
      type: 'SELECT',
      group: 'Finish',
      options: ['Light', 'Medium', 'Full'],
      highlight: true,
      sortOrder: 20,
    },
    {
      slug: 'finish',
      name: 'Finish',
      type: 'SELECT',
      group: 'Finish',
      options: ['Matte', 'Natural', 'Dewy'],
      sortOrder: 21,
    },
    { slug: 'spf', name: 'SPF', type: 'NUMBER', group: 'Finish', min: 0, max: 100, sortOrder: 22 },
    {
      slug: 'volume',
      name: 'Volume',
      type: 'NUMBER',
      unit: 'ml',
      group: 'General',
      highlight: true,
      min: 1,
      max: 1000,
      sortOrder: 2,
    },
    {
      slug: 'cruelty-free',
      name: 'Cruelty-free',
      type: 'BOOLEAN',
      group: 'General',
      highlight: true,
      sortOrder: 3,
    },
    {
      slug: 'shelf-life',
      name: 'Shelf life after opening',
      type: 'NUMBER',
      unit: 'months',
      group: 'General',
      min: 1,
      max: 60,
      sortOrder: 4,
    },
    {
      slug: 'key-ingredients',
      name: 'Key ingredients',
      type: 'TEXT',
      group: 'Ingredients',
      sortOrder: 30,
    },
    ORIGIN,
  ],
  'office-furniture': [
    {
      slug: 'material',
      name: 'Material',
      type: 'TEXT',
      group: 'Construction',
      highlight: true,
      required: true,
      sortOrder: 1,
    },
    { slug: 'seat-material', name: 'Seat', type: 'TEXT', group: 'Construction', sortOrder: 2 },
    {
      slug: 'adjustable-height',
      name: 'Height adjustable',
      type: 'BOOLEAN',
      group: 'Ergonomics',
      highlight: true,
      sortOrder: 10,
    },
    {
      slug: 'lumbar-support',
      name: 'Lumbar support',
      type: 'BOOLEAN',
      group: 'Ergonomics',
      highlight: true,
      sortOrder: 11,
    },
    {
      slug: 'armrests',
      name: 'Armrests',
      type: 'SELECT',
      group: 'Ergonomics',
      options: ['Fixed', 'Adjustable', 'None'],
      sortOrder: 12,
    },
    {
      slug: 'max-load',
      name: 'Maximum load',
      type: 'NUMBER',
      unit: 'kg',
      group: 'Construction',
      highlight: true,
      min: 20,
      max: 400,
      sortOrder: 3,
    },
    {
      slug: 'dimensions',
      name: 'Dimensions (H × W × D)',
      type: 'TEXT',
      group: 'Dimensions',
      sortOrder: 60,
    },
    {
      slug: 'weight',
      name: 'Weight',
      type: 'NUMBER',
      unit: 'kg',
      group: 'Dimensions',
      min: 1,
      max: 200,
      sortOrder: 61,
    },
    {
      slug: 'assembly-required',
      name: 'Assembly required',
      type: 'BOOLEAN',
      group: 'General',
      sortOrder: 70,
    },
    WARRANTY,
  ],
};

/** Values per product slug. Public manufacturer specifications. */
const VALUES: Record<string, Record<string, unknown>> = {
  'iphone-15-pro-256gb': {
    model: 'iPhone 15 Pro',
    'operating-system': 'iOS',
    processor: 'A17 Pro',
    ram: 8,
    'display-size': 6.1,
    'display-type': 'LTPO OLED',
    resolution: '2556 × 1179 (Super Retina XDR)',
    'refresh-rate': 120,
    'rear-camera': '48 MP main + 12 MP ultra-wide + 12 MP 3x telephoto',
    'front-camera': '12 MP TrueDepth',
    'battery-capacity': 3274,
    charging: 'USB-C, up to 27 W wired, 15 W MagSafe',
    'sim-type': 'Dual SIM + eSIM',
    '5g': true,
    nfc: true,
    'usb-type': 'USB-C',
    weight: 187,
    warranty: '1 year manufacturer warranty',
  },
  'dell-inspiron-15-8-512': {
    processor: 'Intel Core i5-1235U',
    'processor-generation': '12th Gen',
    ram: 8,
    'ram-type': 'DDR4',
    'storage-type': 'SSD',
    'storage-capacity': 512,
    'display-size': 15.6,
    resolution: '1920 × 1080 (FHD)',
    'refresh-rate': 120,
    graphics: 'Intel Iris Xe',
    'operating-system': 'Windows 11',
    battery: '54 Wh, up to 8 hours',
    ports: ['USB-C', 'USB-A', 'HDMI', 'SD card', 'Audio jack'],
    wifi: 'Wi-Fi 6',
    bluetooth: 'Bluetooth 5.2',
    webcam: '1080p FHD with privacy shutter',
    keyboard: 'Backlit, spill-resistant',
    weight: 1.65,
    warranty: '1 year onsite warranty',
  },
  'bose-qc-ultra-earbuds': {
    'form-factor': 'In-ear',
    'noise-cancellation': true,
    'driver-size': 9.3,
    'battery-life': 6,
    bluetooth: 'Bluetooth 5.3, multipoint',
    microphone: true,
    'water-resistance': 'IPX4',
    weight: 6.2,
    warranty: '1 year manufacturer warranty',
  },
  'lg-55-4k-oled-tv': {
    'screen-size': 55,
    resolution: '4K',
    'panel-type': 'OLED',
    'refresh-rate': 120,
    hdr: 'Dolby Vision, HDR10, HLG',
    'smart-platform': 'webOS with Magic Remote',
    'hdmi-ports': 4,
    'sound-output': 40,
    'wall-mount': true,
    warranty: '1 year product, 2 years panel',
  },
  'lg-260l-double-door-fridge': {
    capacity: 260,
    'refrigerator-type': 'Double door',
    'number-of-doors': 2,
    'energy-rating': '3 Star',
    'compressor-type': 'Inverter',
    'cooling-technology': 'Multi Air Flow',
    'defrost-system': 'Frost free',
    dimensions: '150 × 60 × 65 cm',
    weight: 52,
    warranty: '1 year product, 10 years compressor',
  },
  'samsung-front-load-washer': {
    capacity: 7,
    'washer-type': 'Front load',
    'spin-speed': 1200,
    'energy-rating': '5 Star',
    'inverter-motor': true,
    'wash-programs': 12,
    dimensions: '85 × 60 × 55 cm',
    weight: 60,
    warranty: '2 years product, 20 years motor',
  },
  'samsung-1-5ton-split-ac': {
    capacity: 1.5,
    'ac-type': 'Split',
    'energy-rating': '3 Star',
    inverter: true,
    'cooling-capacity': 5100,
    refrigerant: 'R32',
    'noise-level': 38,
    warranty: '1 year product, 10 years compressor',
  },
  'nike-drifit-mens-tshirt': {
    gender: 'Men',
    material: '100% recycled polyester',
    fabric: 'Dri-FIT knit',
    fit: 'Regular',
    pattern: 'Solid',
    'sleeve-type': 'Short sleeve',
    'neck-type': 'Crew neck',
    'care-instructions': 'Machine wash cold, do not bleach',
    'country-of-origin': 'Vietnam',
  },
  'nike-womens-drifit-running-top': {
    gender: 'Women',
    material: 'Polyester blend',
    fabric: 'Dri-FIT',
    fit: 'Slim',
    pattern: 'Solid',
    'sleeve-type': 'Short sleeve',
    'neck-type': 'Round neck',
    'care-instructions': 'Machine wash cold, tumble dry low',
    'country-of-origin': 'Thailand',
  },
  'puma-deviate-nitro-elite-2': {
    'shoe-type': 'Racing',
    'upper-material': 'Ultraweave mesh',
    'sole-material': 'PUMAGRIP rubber',
    cushioning: 'NITRO Elite foam with PWRPLATE carbon plate',
    'heel-drop': 8,
    weight: 200,
    closure: 'Lace-up',
    'country-of-origin': 'Vietnam',
  },
  'loreal-true-match-foundation': {
    form: 'Liquid',
    'skin-type': ['Normal', 'Dry', 'Combination'],
    coverage: 'Medium',
    finish: 'Natural',
    spf: 17,
    volume: 30,
    'cruelty-free': false,
    'shelf-life': 24,
    'key-ingredients': 'Hyaluronic acid, glycerin, vitamin E',
    'country-of-origin': 'France',
  },
  'home-centre-ergonomic-office-chair': {
    material: 'Nylon mesh back, fabric seat, steel base',
    'seat-material': 'Moulded foam',
    'adjustable-height': true,
    'lumbar-support': true,
    armrests: 'Adjustable',
    'max-load': 120,
    dimensions: '115 × 66 × 60 cm',
    weight: 15,
    'assembly-required': true,
    warranty: '1 year manufacturer warranty',
  },
};

async function main() {
  const ds = await MarketplaceDataSource.initialize();
  const categories = ds.getRepository(Category);
  const definitions = ds.getRepository(ProductAttribute);
  const products = ds.getRepository(Product);
  const values = ds.getRepository(ProductAttributeValue);
  const attributeValues = new AttributeValuesService(
    definitions,
    values,
    ds.getTreeRepository(Category),
  );

  let defsUpserted = 0;
  for (const [categorySlug, defs] of Object.entries(DEFINITIONS)) {
    const category = await categories.findOne({ where: { slug: categorySlug } });
    if (!category) {
      console.warn(`skip: category ${categorySlug} does not exist`);
      continue;
    }
    for (const d of defs) {
      const existing = await definitions.findOne({
        where: { categoryId: category.id, slug: d.slug },
      });
      const row = definitions.create({
        ...(existing ?? {}),
        categoryId: category.id,
        slug: d.slug,
        name: d.name,
        type: d.type,
        unit: d.unit ?? null,
        groupName: d.group,
        isHighlight: !!d.highlight,
        isRequired: !!d.required,
        isFilterable: existing?.isFilterable ?? true,
        isSearchable: existing?.isSearchable ?? false,
        isVariantAxis: existing?.isVariantAxis ?? false,
        options: d.options ? opts(d.options) : (existing?.options ?? null),
        minValue: d.min == null ? null : String(d.min),
        maxValue: d.max == null ? null : String(d.max),
        sortOrder: d.sortOrder ?? existing?.sortOrder ?? 0,
        isActive: true,
      } as ProductAttribute);
      await definitions.save(row);
      defsUpserted++;
    }
  }
  console.log(`definitions upserted: ${defsUpserted}`);

  const slugs = Object.keys(VALUES);
  const rows = await products.find({
    where: { slug: In(slugs) },
    relations: { category: true, subcategory: true },
  });
  let productsSeeded = 0;
  let valuesWritten = 0;
  for (const slug of slugs) {
    const product = rows.find((p) => p.slug === slug);
    if (!product) {
      console.warn(`skip: product ${slug} does not exist`);
      continue;
    }
    const defs = await attributeValues.definitionsForCategories(
      [product.subcategory?.id, product.category?.id].filter((id): id is string => !!id),
    );
    const inputs = Object.entries(VALUES[slug]).map(([attrSlug, value]) => ({
      slug: attrSlug,
      value,
    }));
    const { rows: valueRows, errors } = AttributeValuesService.validate(defs, inputs, {
      requireAll: true,
    });
    if (errors.length) {
      console.error(`${slug}: ${errors.map((e) => `${e.slug}: ${e.message}`).join(' | ')}`);
      process.exitCode = 1;
      continue;
    }
    await attributeValues.replaceForProduct(product.id, valueRows);
    productsSeeded++;
    valuesWritten += valueRows.length;
  }
  console.log(`products seeded: ${productsSeeded}, values written: ${valuesWritten}`);
  await ds.destroy();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
