import { type MigrationInterface, type QueryRunner } from 'typeorm';

/**
 * KARTSEEK - tables for the gateway-owned entities
 *
 * The API gateway registers ~48 entities of its own (the whole taxi domain, the
 * partner/delivery domain, page layouts, static pages) through
 * DatabaseModule.registerPostgres, which hardcodes synchronize: false. Only
 * bank_offers, exchange_offers and users had ever been created, so every taxi,
 * partner and CMS route answered `relation "public.taxi_drivers" does not
 * exist` - 23 GET routes in the last sweep. Before the gateway fallbacks were
 * removed, those same routes answered 200 with invented data instead.
 *
 * The statements below were generated from the entities with TypeORM's schema
 * builder in **log mode** (scripts/generate-gateway-ddl.ts) and then filtered.
 * That filtering mattered: the full plan also contained twelve destructive
 * statements, among them `ALTER TABLE "users" DROP COLUMN "refreshToken"` and
 * five more dropped user columns, because the gateway's User entity is a
 * narrower view of a table another service owns. Running synchronize here would
 * have silently deleted live columns. Only CREATE statements are kept; the
 * ALTERs against users, bank_offers and exchange_offers are deliberately not
 * applied, since those tables already exist and work.
 */
export class GatewayOwnedTables1786500400000 implements MigrationInterface {
  name = 'GatewayOwnedTables1786500400000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "page_layouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "moduleName" character varying(100) NOT NULL, "pageName" character varying(100) NOT NULL, "sections" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75360f592e7ba64dffd60a31eeb" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'PENDING', "reason" text, "franchise_id" character varying, "region_code" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ff05f54b41711691581d2dd49b7" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_vendor_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendorId" character varying DEFAULT '', "userId" character varying DEFAULT '', "email" character varying DEFAULT '', "role" character varying NOT NULL DEFAULT 'admin', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1198412716c5751f5ccd1cd2d9c" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendorId" character varying, "userId" character varying DEFAULT '', "firstName" character varying DEFAULT '', "lastName" character varying DEFAULT '', "phone" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'PENDING', "onlineStatus" character varying NOT NULL DEFAULT 'OFFLINE', "rating" numeric(3,2) NOT NULL DEFAULT '5', "complianceReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9dd2e5937269189d3571e50c3c8" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendorId" character varying, "plateNumber" character varying DEFAULT '', "model" character varying DEFAULT '', "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "assignedDriverId" character varying, "reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_665f6c0c0b75a9b2be542292f85" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_driver_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" character varying DEFAULT '', "type" character varying NOT NULL, "docUrl" character varying DEFAULT '', "expiryDate" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bd0bf9ba1945f8773721b72fd6e" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_vehicle_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicleId" character varying DEFAULT '', "type" character varying NOT NULL, "docUrl" character varying DEFAULT '', "expiryDate" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_566aa7cf5462e8f7ea95d4fc474" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_rides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" character varying DEFAULT '', "driverId" character varying, "vehicleId" character varying, "vendorId" character varying, "status" character varying NOT NULL DEFAULT 'SEARCHING_DRIVER', "pickupAddress" character varying DEFAULT '', "dropAddress" character varying DEFAULT '', "pickupLat" numeric(10,7) DEFAULT '0', "pickupLng" numeric(10,7) DEFAULT '0', "dropLat" numeric(10,7) DEFAULT '0', "dropLng" numeric(10,7) DEFAULT '0', "paymentMethod" character varying DEFAULT '', "paymentStatus" character varying NOT NULL DEFAULT 'PENDING', "fareEstimate" numeric(10,2) NOT NULL DEFAULT '0', "finalFare" numeric(10,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17933b801e2e94155d1f2b06fc6" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_ride_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "status" character varying DEFAULT '', "reason" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_14d366fe3e73fc6c9846ce7f2c9" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_ride_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "lat" numeric(10,7) DEFAULT '0', "lng" numeric(10,7) DEFAULT '0', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dee283d70b6ef30054d5526d6" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_fare_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "zoneId" character varying DEFAULT '', "vehicleType" character varying NOT NULL, "baseFare" numeric(10,2) DEFAULT '0', "distanceFareRate" numeric(10,2) DEFAULT '0', "timeFareRate" numeric(10,2) DEFAULT '0', "minimumFare" numeric(10,2) DEFAULT '0', "version" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2d4955bb3a8d23a465762f18e06" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_fare_rule_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fareRuleId" character varying DEFAULT '', "version" integer DEFAULT '0', "changeLog" text, "baseFare" numeric(10,2) DEFAULT '0', "distanceFareRate" numeric(10,2) DEFAULT '0', "timeFareRate" numeric(10,2) DEFAULT '0', "minimumFare" numeric(10,2) DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0d6835c5616afca5db1837baab" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_surge_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "zoneId" character varying DEFAULT '', "name" character varying DEFAULT '', "multiplier" numeric(3,2) NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "capLimit" numeric(3,2) NOT NULL DEFAULT '3.5', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_85725f333e27870d19d21645c4e" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_surge_zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying DEFAULT '', "geoJson" jsonb, "activeMultiplier" numeric(3,2) NOT NULL DEFAULT '1', CONSTRAINT "PK_0869c7c21875b3abb6a421e139a" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_surge_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying DEFAULT '', "multiplier" numeric(3,2) DEFAULT '0', "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, CONSTRAINT "PK_e4a2fb2b50b31bf12b305b22b7d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_cancellation_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicleType" character varying DEFAULT '', "feeAfterMinutes" integer NOT NULL DEFAULT '5', "amount" numeric(10,2) DEFAULT '0', CONSTRAINT "PK_0a8af76e7113db7e8259bc116fb" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_waiting_fee_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicleType" character varying DEFAULT '', "freeMinutes" integer NOT NULL DEFAULT '3', "ratePerMinute" numeric(10,2) DEFAULT '0', CONSTRAINT "PK_49e5e49832fc655a8758a3bfdc8" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_fare_breakdowns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "baseFare" numeric(10,2) DEFAULT '0', "distanceFare" numeric(10,2) DEFAULT '0', "timeFare" numeric(10,2) DEFAULT '0', "surgeAdjustment" numeric(10,2) NOT NULL DEFAULT '0', "waitingFee" numeric(10,2) NOT NULL DEFAULT '0', "cancellationFee" numeric(10,2) NOT NULL DEFAULT '0', "tax" numeric(10,2) NOT NULL DEFAULT '0', "platformCommission" numeric(10,2) DEFAULT '0', "vendorCommission" numeric(10,2) DEFAULT '0', "driverEarning" numeric(10,2) DEFAULT '0', CONSTRAINT "PK_e6e642087f20229f76904a27f05" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_driver_earnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" character varying DEFAULT '', "rideId" character varying DEFAULT '', "amount" numeric(10,2) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'UNPAID', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_576d2bc72767b61e08aaf92c5ef" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_vendor_settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendorId" character varying DEFAULT '', "periodStart" TIMESTAMP NOT NULL, "periodEnd" TIMESTAMP NOT NULL, "grossEarnings" numeric(10,2) DEFAULT '0', "commissionDeductions" numeric(10,2) DEFAULT '0', "netPayout" numeric(10,2) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07a754def2bb1db9a7752c4392a" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_commission_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "platformAmount" numeric(10,2) DEFAULT '0', "vendorAmount" numeric(10,2) DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e41562e1aaeb10788bbdf71b430" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_payment_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "transactionId" character varying DEFAULT '', "amount" numeric(10,2) DEFAULT '0', "paymentMethod" character varying DEFAULT '', "status" character varying NOT NULL, "maskedCardNumber" character varying, "auditLog" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_269bbb2e10897b8be69e02148b4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_sos_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "triggeredBy" character varying NOT NULL, "details" text, "status" character varying NOT NULL DEFAULT 'ACTIVE', "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fe3094308b0aa868a3b1548e93c" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying DEFAULT '', "raisedBy" character varying NOT NULL, "reason" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'OPEN', "details" text, "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bd218d971fe93e8d4f8c08e143d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "taxi_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adminUserId" character varying, "vendorUserId" character varying, "action" character varying DEFAULT '', "entityName" character varying DEFAULT '', "entityId" character varying DEFAULT '', "details" text, "reason" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_db005dc952c1e2e3d61e34af757" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_partners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'APPROVED', "rating" numeric(3,2) NOT NULL DEFAULT '5', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_282c55e1a8d521fe45bd419a191" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" character varying DEFAULT '', "deliveryPartnerId" character varying, "serviceType" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'ASSIGNED', "pickupAddress" character varying DEFAULT '', "dropAddress" character varying DEFAULT '', "pickupLat" numeric(10,7) DEFAULT '0', "pickupLng" numeric(10,7) DEFAULT '0', "dropLat" numeric(10,7) DEFAULT '0', "dropLng" numeric(10,7) DEFAULT '0', "isCod" boolean NOT NULL DEFAULT false, "codAmount" numeric(10,2) NOT NULL DEFAULT '0', "deliveryFee" numeric(10,2) NOT NULL DEFAULT '0', "pickupProofUrl" character varying, "dropProofUrl" character varying, "otpCode" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_134fab28ea0e1fb1e666de786bf" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_task_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "taskId" character varying DEFAULT '', "status" character varying DEFAULT '', "reason" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_35d70418040cc260bc88c8f64ac" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_partner_earnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "taskId" character varying DEFAULT '', "amount" numeric(10,2) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'UNPAID', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86694ea0628d09f31b36940132d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_cod_collections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "taskId" character varying DEFAULT '', "collectedAmount" numeric(10,2) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING_REMITTANCE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3fda269edb361e95d947a707297" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "delivery_return_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "originalTaskId" character varying DEFAULT '', "partnerId" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'PENDING', "reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e250b710c6266623581f699eb0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying DEFAULT '', "phone" character varying DEFAULT '', "email" character varying DEFAULT '', "status" character varying NOT NULL DEFAULT 'PENDING', "franchise_id" character varying, "region_code" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_998645b20820e4ab99aeae03b41" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "userId" character varying DEFAULT '', "allowedRoles" jsonb NOT NULL DEFAULT '[]', "activeRole" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01e1d1692cba17ceecf86942a8e" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "permissions" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "UQ_3649421915b796c8eeb74a6843f" UNIQUE ("name"), CONSTRAINT "PK_724d8e60143362fdc3572df617d" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerUserId" character varying DEFAULT '', "roleId" character varying DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa4f970fcba7143142eea6a0df0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "roleType" character varying DEFAULT '', "docType" character varying DEFAULT '', "docUrl" character varying DEFAULT '', "expiryDate" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'PENDING', "reviewNote" text, "reviewedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e66d0f3f5d88856d18749f8b77f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_compliance_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "isCompliant" boolean NOT NULL DEFAULT true, "reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f8400fb3469cf8561b4087d991" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_online_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "roleType" character varying DEFAULT '', "loginTime" TIMESTAMP NOT NULL, "logoutTime" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'ONLINE', CONSTRAINT "PK_14e13959a785b1d545917dada12" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_location_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "lat" numeric(10,7) DEFAULT '0', "lng" numeric(10,7) DEFAULT '0', "heading" numeric(5,2) NOT NULL DEFAULT '0', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ce39d9d89d33b936497ca5a47a2" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_earnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "referenceType" character varying DEFAULT '', "referenceId" character varying DEFAULT '', "amount" numeric(10,2) DEFAULT '0', "tip" numeric(10,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_edcda8ebf3ac39dbb0b278675ac" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "amount" numeric(10,2) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING', "transactionReference" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d6a97f159c25945326fb9585dc0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "partner_sos_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerId" character varying DEFAULT '', "referenceType" character varying, "referenceId" character varying, "lat" numeric(10,7) DEFAULT '0', "lng" numeric(10,7) DEFAULT '0', "status" character varying NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_451127fcc1f3391425cd6cbe0a4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "static_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(100) NOT NULL, "title" character varying(200) NOT NULL, "metaDescription" text, "heroGradient" character varying(200), "heroIcon" character varying(100), "sections" jsonb NOT NULL DEFAULT '[]', "isPublished" boolean NOT NULL DEFAULT true, "version" integer NOT NULL DEFAULT '1', "lastEditedBy" character varying(200), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51d5188719a3fb65679933415ad" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d2bf6a456c0fddfffa3ce667fc" ON "page_layouts" ("moduleName", "pageName")`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_06c8eb8d7d6b0f9cff8dd135a8" ON "static_pages" ("slug")`);
    await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'support_agent', 'finance_manager', 'product_manager', 'customer', 'seller', 'restaurant_seller', 'grocery_seller', 'pharmacy_seller', 'pharmacist', 'doctor', 'driver', 'taxi_driver', 'delivery_driver', 'delivery_boy', 'franchise_owner')`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "static_pages" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_sos_cases" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_payouts" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_earnings" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_location_updates" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_online_sessions" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_compliance_status" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_documents" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_role_assignments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_roles" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partner_users" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "partners" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_return_tasks" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_cod_collections" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_partner_earnings" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_task_status_history" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_tasks" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "delivery_partners" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_audit_logs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_disputes" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_sos_cases" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_payment_records" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_commission_records" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_vendor_settlements" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_driver_earnings" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_fare_breakdowns" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_waiting_fee_rules" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_cancellation_rules" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_surge_events" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_surge_zones" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_surge_rules" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_fare_rule_versions" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_fare_rules" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_ride_locations" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_ride_status_history" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_rides" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_vehicle_documents" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_driver_documents" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_vehicles" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_drivers" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_vendor_users" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "taxi_vendors" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "page_layouts" CASCADE`);
  }
}
