'use client';
import React, { useState } from 'react';
import { DollarSign, Download, ArrowDown, ArrowUp, CheckCircle, FileText } from 'lucide-react';

const payouts = [
  { id: 'PO-001', period: 'May 2026', gross: 120000, commission: 18000, tax: 12000, net: 90000, currency: 'AED', status: 'completed', date: 'Jun 1, 2026' },
  { id: 'PO-002', period: 'Apr 2026', gross: 105000, commission: 15750, tax: 10500, net: 78750, currency: 'AED', status: 'completed', date: 'May 1, 2026' },
  { id: 'PO-003', period: 'Jun 2026', gross: 135000, commission: 20250, tax: 13500, net: 101250, currency: 'AED', status: 'processing', date: 'Jul 1, 2026' },
];

export default function FinancePage() {
  const [toast, setToast] = useState('');
  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000); };

  const downloadReceipt = (payout: typeof payouts[0]) => {
    const content = [
      '═══════════════════════════════════════',
      '        KARTSEEK HOTEL PAYOUT RECEIPT',
      '═══════════════════════════════════════',
      '',
      `Payout ID:       ${payout.id}`,
      `Period:          ${payout.period}`,
      `Date:            ${payout.date}`,
      `Status:          ${payout.status === 'completed' ? 'PAID' : 'PROCESSING'}`,
      '',
      '───────────────────────────────────────',
      `Gross Revenue:   ${payout.currency} ${payout.gross.toLocaleString()}`,
      `Commission (15%):  -${payout.currency} ${payout.commission.toLocaleString()}`,
      `Tax (10%):         -${payout.currency} ${payout.tax.toLocaleString()}`,
      '───────────────────────────────────────',
      `NET PAYOUT:      ${payout.currency} ${payout.net.toLocaleString()}`,
      '',
      'Property: The Grand Palace Hotel',
      'Owner: Ahmed Al Maktoum',
      'Bank: Emirates NBD ****9876',
      '',
      '═══════════════════════════════════════',
      '  Generated by KARTSEEK Hotel Platform',
      '═══════════════════════════════════════',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `KARTSEEK_Payout_${payout.id}_${payout.period.replace(' ', '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast(`Receipt downloaded for ${payout.period}`);
  };

  return (
    <div className="space-y-6">
      <div><h1 className="text-2xl font-bold text-slate-900">Finance &amp; Payouts</h1><p className="text-slate-500 text-sm">Track commission deductions, tax, and payout history.</p></div>
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-4"><p className="text-xs text-emerald-600 font-medium">Total Earned</p><p className="text-2xl font-black text-emerald-700">AED 360K</p></div>
        <div className="bg-red-50 border border-red-100 rounded-xl p-4"><p className="text-xs text-red-600 font-medium">Total Commission</p><p className="text-2xl font-black text-red-700">AED 54K</p></div>
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4"><p className="text-xs text-blue-600 font-medium">Net Received</p><p className="text-2xl font-black text-blue-700">AED 270K</p></div>
      </div>
      <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-50 text-slate-500 border-b border-slate-200">
              <tr><th className="px-5 py-3.5 font-semibold">Period</th><th className="px-5 py-3.5 font-semibold text-right">Gross</th><th className="px-5 py-3.5 font-semibold text-right">Commission</th><th className="px-5 py-3.5 font-semibold text-right">Tax</th><th className="px-5 py-3.5 font-semibold text-right">Net Payout</th><th className="px-5 py-3.5 font-semibold text-center">Status</th><th className="px-5 py-3.5 font-semibold text-center">Invoice</th></tr>
            </thead>
            <tbody className="divide-y divide-slate-100">{payouts.map(p => (
              <tr key={p.id} className="hover:bg-slate-50/50">
                <td className="px-5 py-4 font-bold text-slate-900">{p.period}</td>
                <td className="px-5 py-4 text-right">{p.currency} {p.gross.toLocaleString()}</td>
                <td className="px-5 py-4 text-right text-red-600"><span className="flex items-center justify-end gap-0.5"><ArrowDown className="w-3 h-3" />-{p.currency} {p.commission.toLocaleString()}</span></td>
                <td className="px-5 py-4 text-right text-amber-600">-{p.currency} {p.tax.toLocaleString()}</td>
                <td className="px-5 py-4 text-right font-bold text-emerald-600"><span className="flex items-center justify-end gap-0.5"><ArrowUp className="w-3 h-3" />{p.currency} {p.net.toLocaleString()}</span></td>
                <td className="px-5 py-4 text-center"><span className={`px-2.5 py-1 rounded-full text-xs font-bold ${p.status === 'completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{p.status === 'completed' ? 'Paid' : 'Processing'}</span></td>
                <td className="px-5 py-4 text-center"><button title="Download receipt" onClick={() => downloadReceipt(p)} className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 transition-colors hover:text-rose-600"><Download className="w-3.5 h-3.5" /></button></td>
              </tr>
            ))}</tbody>
          </table>
        </div>
      </div>

      {toast && (
        <div className="fixed bottom-6 right-6 bg-emerald-600 text-white px-5 py-3 rounded-xl shadow-lg flex items-center gap-2 z-50">
          <CheckCircle className="w-4 h-4" /><span className="text-sm font-bold">{toast}</span>
        </div>
      )}
    </div>
  );
}
