// Storefront pages must not import from this file. The trust strip and the
// FAQ moved to `marketplace/home-content.ts`; what remains here seeds the
// admin console's in-memory marketplace context only.
/* cSpell:words Innerwear Décor Organisation Flowy Domyos Sixer cultsport Cultsport funskool Funskool chicco Chicco daikin Daikin uniqlo Uniqlo airdopes Airdopes crocs Crocs nord mamaearth Mamaearth Thermosteel */
import type {
  RegionTargeted,
  HomeProduct,
  HomeBrand,
  HomeCategory,
  CampaignBanner,
  CountryBanner,
} from '@/lib/marketplace/types';
import { forRegion } from '@/lib/marketplace/pricing';

// apps/web/src/lib/mock/marketplace-home.ts
// Premium marketplace homepage data — 20 categories, rich product catalog, campaigns
import { getProductImage, getCategoryImage } from './marketplace-images';

// ── Type Definitions ──────────────────────────────────────────────────────────

// ── 20 Categories with Subcategories ──────────────────────────────────────────

export const CATEGORIES: HomeCategory[] = [
  {
    id: 'mobiles-tablets',
    label: 'Mobiles & Tablets',
    iconName: 'Smartphone',
    color: 'bg-blue-50 text-blue-600',
    productCount: 12400,
    subcategories: [
      'Smartphones',
      'Tablets',
      'Feature Phones',
      'Mobile Accessories',
      'Cases & Covers',
      'Screen Protectors',
      'Power Banks',
      'Chargers & Cables',
    ],
  },
  {
    id: 'electronics',
    label: 'Electronics',
    iconName: 'Laptop',
    color: 'bg-indigo-50 text-indigo-600',
    productCount: 18200,
    subcategories: [
      'Laptops',
      'Headphones & Earbuds',
      'Cameras',
      'Smart Watches',
      'Speakers',
      'Gaming Consoles',
      'Drones',
      'Storage Devices',
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion',
    iconName: 'Shirt',
    color: 'bg-pink-50 text-pink-600',
    productCount: 45600,
    subcategories: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Wear",
      'Ethnic Wear',
      'Winter Wear',
      'Sportswear',
      'Innerwear',
      'Accessories',
    ],
  },
  {
    id: 'beauty',
    label: 'Beauty & Personal Care',
    iconName: 'Sparkles',
    color: 'bg-rose-50 text-rose-600',
    productCount: 22100,
    subcategories: [
      'Skincare',
      'Haircare',
      'Makeup',
      'Fragrances',
      'Personal Care',
      "Men's Grooming",
      'Bath & Body',
      'Luxury Beauty',
    ],
  },
  {
    id: 'home-kitchen',
    label: 'Home & Kitchen',
    iconName: 'Sofa',
    color: 'bg-amber-50 text-amber-600',
    productCount: 31800,
    subcategories: [
      'Kitchen Appliances',
      'Cookware',
      'Décor',
      'Bedding',
      'Storage & Organisation',
      'Lighting',
      'Dining & Serving',
      'Cleaning Supplies',
    ],
  },
  {
    id: 'appliances',
    label: 'Appliances',
    iconName: 'Tv',
    color: 'bg-sky-50 text-sky-600',
    productCount: 8900,
    subcategories: [
      'TVs',
      'Washing Machines',
      'Refrigerators',
      'Air Conditioners',
      'Microwaves',
      'Water Purifiers',
      'Chimneys & Hobs',
      'Geysers',
    ],
  },
  {
    id: 'furniture',
    label: 'Furniture',
    iconName: 'Armchair',
    color: 'bg-orange-50 text-orange-600',
    productCount: 14500,
    subcategories: [
      'Living Room',
      'Bedroom',
      'Dining',
      'Office Furniture',
      'Outdoor',
      'Mattresses',
      'Kids Furniture',
      'Storage',
    ],
  },
  {
    id: 'sports',
    label: 'Sports & Fitness',
    iconName: 'Dumbbell',
    color: 'bg-emerald-50 text-emerald-600',
    productCount: 11200,
    subcategories: [
      'Gym Equipment',
      'Running Shoes',
      'Cricket',
      'Football',
      'Yoga & Meditation',
      'Cycling',
      'Swimming',
      'Nutrition & Supplements',
    ],
  },
  {
    id: 'books',
    label: 'Books & Stationery',
    iconName: 'BookOpen',
    color: 'bg-teal-50 text-teal-600',
    productCount: 28900,
    subcategories: [
      'Fiction',
      'Non-Fiction',
      'Academic & Textbooks',
      'Self-Help',
      'Comics & Manga',
      'eBooks & Audiobooks',
      'Stationery',
      'Art Supplies',
    ],
  },
  {
    id: 'toys-baby',
    label: 'Toys & Baby Products',
    iconName: 'Baby',
    color: 'bg-purple-50 text-purple-600',
    productCount: 16700,
    subcategories: [
      'Toys & Games',
      'Baby Gear',
      'Diapers & Wipes',
      'Feeding Essentials',
      'Nursery',
      'School Supplies',
      'Remote Control Toys',
      'Educational Toys',
    ],
  },
  {
    id: 'automotive',
    label: 'Automotive Accessories',
    iconName: 'Car',
    color: 'bg-slate-100 text-slate-600',
    productCount: 7800,
    subcategories: [
      'Car Accessories',
      'Bike Accessories',
      'Helmets',
      'Car Electronics',
      'Oils & Fluids',
      'Tools & Equipment',
      'Tyre & Alloys',
      'Car Care',
    ],
  },
  {
    id: 'health-wellness',
    label: 'Health & Wellness',
    iconName: 'Heart',
    color: 'bg-red-50 text-red-600',
    productCount: 9400,
    subcategories: [
      'Vitamins & Supplements',
      'Ayurvedic',
      'Fitness Devices',
      'Medical Devices',
      'Health Drinks',
      'Immunity Boosters',
      'Weight Management',
      'Elder Care',
    ],
  },
  {
    id: 'watches',
    label: 'Watches & Accessories',
    iconName: 'Watch',
    color: 'bg-yellow-50 text-yellow-700',
    productCount: 13600,
    subcategories: [
      "Men's Watches",
      "Women's Watches",
      'Smartwatches',
      'Luxury Watches',
      'Sunglasses',
      'Belts',
      'Wallets',
      'Jewellery',
    ],
  },
  {
    id: 'bags-travel',
    label: 'Bags & Travel',
    iconName: 'Briefcase',
    color: 'bg-cyan-50 text-cyan-600',
    productCount: 8200,
    subcategories: [
      'Backpacks',
      'Handbags',
      'Luggage',
      'Travel Accessories',
      'Laptop Bags',
      'Duffel Bags',
      'Wallets & Clutches',
      'Waist Bags',
    ],
  },
  {
    id: 'footwear',
    label: 'Footwear',
    iconName: 'Footprints',
    color: 'bg-lime-50 text-lime-700',
    productCount: 19800,
    subcategories: [
      "Men's Casual",
      "Men's Formal",
      "Women's Flats",
      "Women's Heels",
      'Sports Shoes',
      'Sandals & Slippers',
      "Kids' Shoes",
      'Boots',
    ],
  },
  {
    id: 'computers',
    label: 'Computers & Accessories',
    iconName: 'Monitor',
    color: 'bg-violet-50 text-violet-600',
    productCount: 10200,
    subcategories: [
      'Desktops',
      'Monitors',
      'Keyboards & Mice',
      'Printers',
      'Routers',
      'External Storage',
      'PC Components',
      'Software',
    ],
  },
  {
    id: 'office-supplies',
    label: 'Office Supplies',
    iconName: 'Paperclip',
    color: 'bg-gray-50 text-gray-600',
    productCount: 5400,
    subcategories: [
      'Writing Instruments',
      'Paper Products',
      'Filing & Organisation',
      'Desk Accessories',
      'Labels & Tapes',
      'Presentation Supplies',
      'Binding & Laminating',
      'Break Room Supplies',
    ],
  },
  {
    id: 'pet-supplies',
    label: 'Pet Supplies',
    iconName: 'PawPrint',
    color: 'bg-amber-50 text-amber-700',
    productCount: 6100,
    subcategories: [
      'Dog Food',
      'Cat Food',
      'Pet Toys',
      'Grooming',
      'Beds & Furniture',
      'Collars & Leashes',
      'Health & Wellness',
      'Aquarium Supplies',
    ],
  },
  {
    id: 'baby-care',
    label: 'Baby Care',
    iconName: 'BabyIcon',
    color: 'bg-pink-50 text-pink-500',
    productCount: 7200,
    subcategories: [
      'Diapers',
      'Baby Food',
      'Bathing & Skincare',
      'Clothing',
      'Strollers & Carriers',
      'Cribs & Bedding',
      'Safety & Proofing',
      'Feeding Bottles',
    ],
  },
  {
    id: 'grocery-essentials',
    label: 'Grocery Essentials',
    iconName: 'ShoppingBasket',
    color: 'bg-green-50 text-green-600',
    productCount: 24500,
    subcategories: [
      'Snacks & Beverages',
      'Dry Fruits & Nuts',
      'Cooking Essentials',
      'Breakfast & Cereals',
      'Packaged Foods',
      'Personal Care',
      'Cleaning & Household',
      'Pet Food',
    ],
  },
];

// ── Flash Deals ────────────────────────────────────────────────────────────

export const FLASH_DEALS: HomeProduct[] = [
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: 'iPhone 15 Pro (256GB) – Titanium Blue',
    brand: 'Apple',
    price: 115900,
    mrp: 134900,
    rating: 4.9,
    reviews: '12.4k',
    badge: '25% OFF',
    badgeColor: 'bg-red-500',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: 'Tomorrow',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Dell XPS 13 Plus (16GB, 512GB SSD)',
    brand: 'Dell',
    price: 145000,
    mrp: 160000,
    rating: 4.7,
    reviews: '892',
    badge: '10% OFF',
    badgeColor: 'bg-orange-500',
    icon: 'Laptop',
    category: 'electronics',
    delivery: '2-3 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    brand: 'Sony',
    price: 24990,
    mrp: 34990,
    rating: 4.8,
    reviews: '8.2k',
    badge: '29% OFF',
    badgeColor: 'bg-red-500',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: 'Samsung Galaxy S24 Ultra (12GB, 256GB)',
    brand: 'Samsung',
    price: 119999,
    mrp: 134999,
    rating: 4.6,
    reviews: '5.1k',
    badge: '11% OFF',
    badgeColor: 'bg-orange-500',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: '2-3 days',
  },
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'Dyson Airwrap Multi-Styler Complete',
    brand: 'Dyson',
    price: 44900,
    mrp: 49900,
    rating: 4.8,
    reviews: '3.4k',
    badge: '10% OFF',
    badgeColor: 'bg-orange-500',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: '3-4 days',
  },
];

// ── Electronics Section ────────────────────────────────────────────────────

export const ELECTRONICS_PRODUCTS: HomeProduct[] = [
  {
    id: '071dbd07-5a4d-4428-9cd2-24eff0ef928e',
    title: 'MacBook Air M3 (8GB, 256GB SSD)',
    brand: 'Apple',
    price: 114900,
    mrp: 119900,
    rating: 4.8,
    reviews: '3.2k',
    icon: 'Laptop',
    category: 'electronics',
    delivery: '2-3 days',
  },
  {
    id: 'd4f9a618-b26e-4031-8a6a-2010153ea2c0',
    title: 'iPad Pro 12.9" M2 Chip (256GB, WiFi)',
    brand: 'Apple',
    price: 112900,
    mrp: 124900,
    rating: 4.9,
    reviews: '2.1k',
    icon: 'Tablet',
    category: 'electronics',
    delivery: '3-4 days',
  },
  {
    id: 'c917c4ed-a17c-45e2-a47b-b1ec18e36cd6',
    title: 'Apple AirPods Pro 2nd Gen (USB-C)',
    brand: 'Apple',
    price: 20900,
    mrp: 24900,
    rating: 4.7,
    reviews: '15k',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: '90ec57f2-5823-43c0-818a-1860ae679634',
    title: 'Samsung Galaxy Tab S9 FE (128GB)',
    brand: 'Samsung',
    price: 34999,
    mrp: 44999,
    rating: 4.5,
    reviews: '1.8k',
    icon: 'Tablet',
    category: 'electronics',
    delivery: '2-3 days',
  },
  {
    id: '3e146924-4876-4de0-967e-19e836208bb6',
    title: 'JBL Flip 6 Portable Bluetooth Speaker',
    brand: 'JBL',
    price: 8999,
    mrp: 12999,
    rating: 4.6,
    reviews: '9.3k',
    icon: 'Speaker',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: '6b361b3e-426e-4027-9f42-e6273128bd99',
    title: 'OnePlus 12 5G (12GB, 256GB) – Flowy Emerald',
    brand: 'OnePlus',
    price: 57999,
    mrp: 64999,
    rating: 4.5,
    reviews: '4.6k',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: '2-3 days',
  },
  {
    id: '45627fbd-6661-4ddc-9239-0bf354dec632',
    title: 'LG C3 55" 4K OLED Evo Smart TV',
    brand: 'LG',
    price: 99990,
    mrp: 164990,
    rating: 4.8,
    reviews: '1.4k',
    icon: 'Tv',
    category: 'appliances',
    delivery: '5-7 days',
  },
  {
    id: 'd3f12b49-fed6-4544-a889-99a874b823c2',
    title: 'Canon EOS R50 Mirrorless Camera Kit',
    brand: 'Canon',
    price: 66990,
    mrp: 75990,
    rating: 4.7,
    reviews: '680',
    icon: 'Camera',
    category: 'electronics',
    delivery: '3-4 days',
  },
];

// ── Fashion Section ────────────────────────────────────────────────────────

export const FASHION_PRODUCTS: HomeProduct[] = [
  {
    id: '8e8af2a2-867c-426e-9e54-0a9144ab1e1b',
    title: 'Nike Air Max 270 React – Black/White',
    brand: 'Nike',
    price: 11995,
    mrp: 15995,
    rating: 4.6,
    reviews: '7.2k',
    icon: 'Shirt',
    category: 'footwear',
    delivery: '2-3 days',
  },
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: "Levi's 501 Original Fit Jeans – Dark Wash",
    brand: "Levi's",
    price: 3499,
    mrp: 4999,
    rating: 4.4,
    reviews: '11k',
    icon: 'Shirt',
    category: 'fashion',
    delivery: '3-4 days',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Ray-Ban Aviator Classic (Gold/Green)',
    brand: 'Ray-Ban',
    price: 8490,
    mrp: 9990,
    rating: 4.7,
    reviews: '4.5k',
    icon: 'Glasses',
    category: 'watches',
    delivery: '2-3 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Adidas Ultraboost 22 Running Shoes',
    brand: 'Adidas',
    price: 12999,
    mrp: 16999,
    rating: 4.5,
    reviews: '3.8k',
    icon: 'Shirt',
    category: 'footwear',
    delivery: '3-4 days',
  },
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: 'ZARA Tailored Double-Breasted Blazer',
    brand: 'ZARA',
    price: 5990,
    mrp: 7990,
    rating: 4.3,
    reviews: '1.2k',
    icon: 'Shirt',
    category: 'fashion',
    delivery: '4-5 days',
  },
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'H&M Floral Midi Wrap Dress – Emerald',
    brand: 'H&M',
    price: 2499,
    mrp: 3999,
    rating: 4.2,
    reviews: '2.8k',
    icon: 'Shirt',
    category: 'fashion',
    delivery: '3-4 days',
  },
  {
    id: '071dbd07-5a4d-4428-9cd2-24eff0ef928e',
    title: 'Puma Essentials Logo Tee – Navy Blue',
    brand: 'Puma',
    price: 899,
    mrp: 1499,
    rating: 4.4,
    reviews: '6.1k',
    icon: 'Shirt',
    category: 'fashion',
    delivery: 'Tomorrow',
  },
  {
    id: 'd4f9a618-b26e-4031-8a6a-2010153ea2c0',
    title: 'Woodland Genuine Leather Ankle Boots',
    brand: 'Woodland',
    price: 4495,
    mrp: 5995,
    rating: 4.5,
    reviews: '3.3k',
    icon: 'Shirt',
    category: 'footwear',
    delivery: '3-4 days',
  },
];

// ── Home & Kitchen Section ─────────────────────────────────────────────────

export const HOME_PRODUCTS: HomeProduct[] = [
  {
    id: 'c917c4ed-a17c-45e2-a47b-b1ec18e36cd6',
    title: 'Dyson V12 Detect Slim Cordless Vacuum',
    brand: 'Dyson',
    price: 42900,
    mrp: 52900,
    rating: 4.7,
    reviews: '2.1k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: '3-5 days',
  },
  {
    id: '90ec57f2-5823-43c0-818a-1860ae679634',
    title: 'Prestige Svachh 5L Pressure Cooker',
    brand: 'Prestige',
    price: 2149,
    mrp: 3050,
    rating: 4.5,
    reviews: '18k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: 'Tomorrow',
  },
  {
    id: '3e146924-4876-4de0-967e-19e836208bb6',
    title: 'IKEA KALLAX 4x2 Shelf Unit – White',
    brand: 'IKEA',
    price: 7990,
    mrp: 9990,
    rating: 4.6,
    reviews: '1.5k',
    icon: 'Sofa',
    category: 'furniture',
    delivery: '5-7 days',
  },
  {
    id: '6b361b3e-426e-4027-9f42-e6273128bd99',
    title: 'Philips Digital XL Airfryer HD9270',
    brand: 'Philips',
    price: 9999,
    mrp: 14995,
    rating: 4.6,
    reviews: '5.4k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: '2-3 days',
  },
  {
    id: '45627fbd-6661-4ddc-9239-0bf354dec632',
    title: 'Wipro 9W Smart LED Bulb (4-Pack)',
    brand: 'Wipro',
    price: 1299,
    mrp: 1999,
    rating: 4.3,
    reviews: '8.7k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: 'Tomorrow',
  },
  {
    id: 'd3f12b49-fed6-4544-a889-99a874b823c2',
    title: 'Borosil 12-Piece Glass Storage Set',
    brand: 'Borosil',
    price: 1849,
    mrp: 2499,
    rating: 4.4,
    reviews: '3.6k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: '2-3 days',
  },
];

// ── Beauty & Personal Care ─────────────────────────────────────────────────

export const BEAUTY_PRODUCTS: HomeProduct[] = [
  {
    id: '8e8af2a2-867c-426e-9e54-0a9144ab1e1b',
    title: 'MAC Matte Lipstick – Ruby Woo',
    brand: 'MAC',
    price: 1750,
    mrp: 1950,
    rating: 4.7,
    reviews: '22k',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: '2-3 days',
  },
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: 'Cetaphil Gentle Skin Cleanser (500ml)',
    brand: 'Cetaphil',
    price: 749,
    mrp: 999,
    rating: 4.5,
    reviews: '28k',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: 'Tomorrow',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Forest Essentials Sandalwood Face Cream',
    brand: 'Forest Essentials',
    price: 2475,
    mrp: 2750,
    rating: 4.6,
    reviews: '4.1k',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: '3-4 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Philips BT3211 Beard Trimmer',
    brand: 'Philips',
    price: 1499,
    mrp: 1995,
    rating: 4.3,
    reviews: '14k',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: 'Tomorrow',
  },
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: "L'Oréal Hyaluronic Acid Face Serum",
    brand: "L'Oréal",
    price: 599,
    mrp: 999,
    rating: 4.4,
    reviews: '9.8k',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: '2-3 days',
  },
];

// ── Sports & Fitness ───────────────────────────────────────────────────────

export const SPORTS_PRODUCTS: HomeProduct[] = [
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'Nike Air Zoom Pegasus 40 Running Shoes',
    brand: 'Nike',
    price: 9995,
    mrp: 11895,
    rating: 4.5,
    reviews: '5.6k',
    icon: 'Dumbbell',
    category: 'sports',
    delivery: '2-3 days',
  },
  {
    id: '071dbd07-5a4d-4428-9cd2-24eff0ef928e',
    title: 'Decathlon Domyos TPE Yoga Mat 8mm',
    brand: 'Decathlon',
    price: 999,
    mrp: 1499,
    rating: 4.4,
    reviews: '12k',
    icon: 'Dumbbell',
    category: 'sports',
    delivery: 'Tomorrow',
  },
  {
    id: 'd4f9a618-b26e-4031-8a6a-2010153ea2c0',
    title: 'SG HP Sixer English Willow Cricket Bat',
    brand: 'SG',
    price: 4499,
    mrp: 5999,
    rating: 4.6,
    reviews: '2.3k',
    icon: 'Dumbbell',
    category: 'sports',
    delivery: '3-4 days',
  },
  {
    id: 'c917c4ed-a17c-45e2-a47b-b1ec18e36cd6',
    title: 'Fitbit Charge 6 Fitness Tracker',
    brand: 'Fitbit',
    price: 14999,
    mrp: 16999,
    rating: 4.5,
    reviews: '3.8k',
    icon: 'Dumbbell',
    category: 'sports',
    delivery: '2-3 days',
  },
  {
    id: '90ec57f2-5823-43c0-818a-1860ae679634',
    title: 'Cultsport Aero Plus 26T Mountain Bike',
    brand: 'Cultsport',
    price: 12999,
    mrp: 18999,
    rating: 4.3,
    reviews: '1.1k',
    icon: 'Dumbbell',
    category: 'sports',
    delivery: '5-7 days',
  },
];

// ── Toys & Baby ────────────────────────────────────────────────────────────

export const TOYS_PRODUCTS: HomeProduct[] = [
  {
    id: '3e146924-4876-4de0-967e-19e836208bb6',
    title: 'LEGO Technic Bugatti Chiron 42083',
    brand: 'LEGO',
    price: 29999,
    mrp: 34999,
    rating: 4.9,
    reviews: '1.8k',
    icon: 'Baby',
    category: 'toys-baby',
    delivery: '3-5 days',
  },
  {
    id: '6b361b3e-426e-4027-9f42-e6273128bd99',
    title: 'Pampers Premium Care Pants (L, 44 Count)',
    brand: 'Pampers',
    price: 1149,
    mrp: 1399,
    rating: 4.5,
    reviews: '42k',
    icon: 'Baby',
    category: 'baby-care',
    delivery: 'Tomorrow',
  },
  {
    id: '45627fbd-6661-4ddc-9239-0bf354dec632',
    title: 'Funskool Monopoly – Classic Edition',
    brand: 'Funskool',
    price: 599,
    mrp: 999,
    rating: 4.3,
    reviews: '8.7k',
    icon: 'Baby',
    category: 'toys-baby',
    delivery: '2-3 days',
  },
  {
    id: 'd3f12b49-fed6-4544-a889-99a874b823c2',
    title: 'Chicco Bravo LE Quick-Fold Stroller',
    brand: 'Chicco',
    price: 18999,
    mrp: 24999,
    rating: 4.7,
    reviews: '1.2k',
    icon: 'Baby',
    category: 'baby-care',
    delivery: '5-7 days',
  },
];

// ── Appliances ─────────────────────────────────────────────────────────────

export const APPLIANCES_PRODUCTS: HomeProduct[] = [
  {
    id: '8e8af2a2-867c-426e-9e54-0a9144ab1e1b',
    title: 'LG C3 55" 4K OLED Evo Smart TV',
    brand: 'LG',
    price: 99990,
    mrp: 164990,
    rating: 4.8,
    reviews: '1.4k',
    icon: 'Tv',
    category: 'appliances',
    delivery: '5-7 days',
  },
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: 'Samsung EcoBubble 8kg Front Load',
    brand: 'Samsung',
    price: 37990,
    mrp: 46990,
    rating: 4.5,
    reviews: '4.2k',
    icon: 'Tv',
    category: 'appliances',
    delivery: '5-7 days',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Whirlpool 265L Frost Free Refrigerator',
    brand: 'Whirlpool',
    price: 24990,
    mrp: 31990,
    rating: 4.4,
    reviews: '6.1k',
    icon: 'Tv',
    category: 'appliances',
    delivery: '5-7 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Daikin 1.5 Ton 5-Star Inverter Split AC',
    brand: 'Daikin',
    price: 42990,
    mrp: 56990,
    rating: 4.6,
    reviews: '3.5k',
    icon: 'Tv',
    category: 'appliances',
    delivery: '5-7 days',
  },
];

// ── NEW ARRIVALS ───────────────────────────────────────────────────────────

export const NEW_ARRIVALS: HomeProduct[] = [
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: 'Google Pixel 9 Pro (256GB) – Obsidian',
    brand: 'Google',
    price: 99999,
    mrp: 109999,
    rating: 4.7,
    reviews: '420',
    badge: 'NEW',
    badgeColor: 'bg-blue-600',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: '2-3 days',
  },
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'Samsung Galaxy Ring – Size 9, Titanium',
    brand: 'Samsung',
    price: 35999,
    mrp: 38999,
    rating: 4.4,
    reviews: '180',
    badge: 'NEW',
    badgeColor: 'bg-blue-600',
    icon: 'Watch',
    category: 'watches',
    delivery: '3-4 days',
  },
  {
    id: '071dbd07-5a4d-4428-9cd2-24eff0ef928e',
    title: 'Mac Studio M4 Max (64GB, 1TB SSD)',
    brand: 'Apple',
    price: 299900,
    mrp: 299900,
    rating: 4.9,
    reviews: '95',
    badge: 'NEW',
    badgeColor: 'bg-blue-600',
    icon: 'Monitor',
    category: 'computers',
    delivery: '5-7 days',
  },
  {
    id: 'd4f9a618-b26e-4031-8a6a-2010153ea2c0',
    title: 'Uniqlo Hybrid Down Parka – Black',
    brand: 'Uniqlo',
    price: 5990,
    mrp: 7990,
    rating: 4.5,
    reviews: '310',
    badge: 'NEW',
    badgeColor: 'bg-blue-600',
    icon: 'Shirt',
    category: 'fashion',
    delivery: '3-4 days',
  },
  {
    id: 'c917c4ed-a17c-45e2-a47b-b1ec18e36cd6',
    title: 'Nothing CMF Watch Pro 2 – Dark Grey',
    brand: 'Nothing',
    price: 4999,
    mrp: 4999,
    rating: 4.3,
    reviews: '1.2k',
    badge: 'NEW',
    badgeColor: 'bg-blue-600',
    icon: 'Watch',
    category: 'watches',
    delivery: 'Tomorrow',
  },
];

// ── BEST SELLERS ───────────────────────────────────────────────────────────

export const BEST_SELLERS: HomeProduct[] = [
  {
    id: '90ec57f2-5823-43c0-818a-1860ae679634',
    title: 'boAt Airdopes 141 TWS Earbuds',
    brand: 'boAt',
    price: 1099,
    mrp: 4490,
    rating: 4.1,
    reviews: '145k',
    badge: '#1 BEST SELLER',
    badgeColor: 'bg-amber-600',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: '3e146924-4876-4de0-967e-19e836208bb6',
    title: 'Noise ColorFit Ultra 3 Smartwatch',
    brand: 'Noise',
    price: 2999,
    mrp: 6999,
    rating: 4.2,
    reviews: '89k',
    badge: '#2 BEST SELLER',
    badgeColor: 'bg-amber-600',
    icon: 'Watch',
    category: 'watches',
    delivery: 'Tomorrow',
  },
  {
    id: '6b361b3e-426e-4027-9f42-e6273128bd99',
    title: 'Cetaphil Gentle Skin Cleanser (250ml)',
    brand: 'Cetaphil',
    price: 449,
    mrp: 599,
    rating: 4.5,
    reviews: '52k',
    badge: '#3 BEST SELLER',
    badgeColor: 'bg-amber-600',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: 'Tomorrow',
  },
  {
    id: '45627fbd-6661-4ddc-9239-0bf354dec632',
    title: 'Amazon Fire TV Stick 4K Max (2nd Gen)',
    brand: 'Amazon',
    price: 4999,
    mrp: 7999,
    rating: 4.5,
    reviews: '62k',
    badge: '#4 BEST SELLER',
    badgeColor: 'bg-amber-600',
    icon: 'Tv',
    category: 'appliances',
    delivery: 'Tomorrow',
  },
  {
    id: 'd3f12b49-fed6-4544-a889-99a874b823c2',
    title: 'Puma Essentials Logo Tee – Black',
    brand: 'Puma',
    price: 699,
    mrp: 1499,
    rating: 4.4,
    reviews: '34k',
    badge: '#5 BEST SELLER',
    badgeColor: 'bg-amber-600',
    icon: 'Shirt',
    category: 'fashion',
    delivery: 'Tomorrow',
  },
];

// ── RECOMMENDED FOR YOU ────────────────────────────────────────────────────

export const RECOMMENDED: HomeProduct[] = [
  {
    id: '8e8af2a2-867c-426e-9e54-0a9144ab1e1b',
    title: 'Kindle Paperwhite (16GB) – Black',
    brand: 'Amazon',
    price: 14999,
    mrp: 16999,
    rating: 4.7,
    reviews: '18k',
    icon: 'BookOpen',
    category: 'electronics',
    delivery: '2-3 days',
  },
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: 'Xiaomi Smart Band 8 Pro – Black',
    brand: 'Xiaomi',
    price: 3499,
    mrp: 4999,
    rating: 4.3,
    reviews: '7.2k',
    icon: 'Watch',
    category: 'watches',
    delivery: 'Tomorrow',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Crocs Classic Clog – Army Green',
    brand: 'Crocs',
    price: 2697,
    mrp: 4495,
    rating: 4.4,
    reviews: '35k',
    icon: 'Shirt',
    category: 'footwear',
    delivery: '2-3 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Instant Pot Duo 7-in-1 (6 Quart)',
    brand: 'Instant Pot',
    price: 6999,
    mrp: 13999,
    rating: 4.6,
    reviews: '21k',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: '3-4 days',
  },
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: 'Samsung Galaxy Buds2 Pro – Graphite',
    brand: 'Samsung',
    price: 9999,
    mrp: 17999,
    rating: 4.5,
    reviews: '6.1k',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
];

// ── SPONSORED PRODUCTS ─────────────────────────────────────────────────────

export const SPONSORED_PRODUCTS: HomeProduct[] = [
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'OnePlus Nord CE 4 Lite 5G (8GB, 128GB)',
    brand: 'OnePlus',
    price: 19999,
    mrp: 22999,
    rating: 4.3,
    reviews: '3.4k',
    badge: 'SPONSORED',
    badgeColor: 'bg-slate-600',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: '2-3 days',
  },
  {
    id: '071dbd07-5a4d-4428-9cd2-24eff0ef928e',
    title: 'Realme Buds Air 5 Pro ANC Earbuds',
    brand: 'Realme',
    price: 3999,
    mrp: 4999,
    rating: 4.2,
    reviews: '8.9k',
    badge: 'SPONSORED',
    badgeColor: 'bg-slate-600',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: 'd4f9a618-b26e-4031-8a6a-2010153ea2c0',
    title: 'Mamaearth Vitamin C Skincare Gift Set',
    brand: 'Mamaearth',
    price: 1299,
    mrp: 1999,
    rating: 4.1,
    reviews: '15k',
    badge: 'SPONSORED',
    badgeColor: 'bg-slate-600',
    icon: 'Sparkles',
    category: 'beauty',
    delivery: '2-3 days',
  },
  {
    id: 'c917c4ed-a17c-45e2-a47b-b1ec18e36cd6',
    title: 'boAt Stone 352 Portable Speaker',
    brand: 'boAt',
    price: 1499,
    mrp: 2990,
    rating: 4.3,
    reviews: '22k',
    badge: 'SPONSORED',
    badgeColor: 'bg-slate-600',
    icon: 'Speaker',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: '90ec57f2-5823-43c0-818a-1860ae679634',
    title: 'Milton Thermosteel Duo 500ml Flask',
    brand: 'Milton',
    price: 599,
    mrp: 1099,
    rating: 4.5,
    reviews: '31k',
    badge: 'SPONSORED',
    badgeColor: 'bg-slate-600',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: 'Tomorrow',
  },
];

// ── Brand Promotions ───────────────────────────────────────────────────────

export const BRAND_PROMOS: Record<string, HomeBrand[]> = {
  electronics: [
    {
      id: 'apple',
      name: 'Apple',
      tagline: 'Think Different',
      discount: 'Up to 20% Off',
      color: 'bg-gradient-to-br from-slate-900 to-slate-700',
      textColor: 'text-white',
    },
    {
      id: 'samsung',
      name: 'Samsung',
      tagline: 'Galaxy of Possibilities',
      discount: 'Starting',
      discountAmount: 12999,
      discountType: 'starting',
      color: 'bg-gradient-to-br from-blue-800 to-blue-600',
      textColor: 'text-white',
    },
    {
      id: 'sony',
      name: 'Sony',
      tagline: 'Be Moved',
      discount: 'Flat 30% Off',
      color: 'bg-gradient-to-br from-slate-800 to-zinc-700',
      textColor: 'text-white',
    },
    {
      id: 'oneplus',
      name: 'OnePlus',
      tagline: 'Never Settle',
      discount: 'Up to',
      discountAmount: 8000,
      discountType: 'upto',
      color: 'bg-gradient-to-br from-red-700 to-red-500',
      textColor: 'text-white',
    },
  ],
  fashion: [
    {
      id: 'nike',
      name: 'Nike',
      tagline: 'Just Do It',
      discount: 'Min 30% Off',
      color: 'bg-gradient-to-br from-orange-600 to-orange-400',
      textColor: 'text-white',
    },
    {
      id: 'adidas',
      name: 'Adidas',
      tagline: 'Impossible Is Nothing',
      discount: 'Up to 50% Off',
      color: 'bg-gradient-to-br from-slate-900 to-slate-700',
      textColor: 'text-white',
    },
    {
      id: 'levis',
      name: "Levi's",
      tagline: 'Quality Never Goes Out of Style',
      discount: 'Buy 2 Get 1',
      color: 'bg-gradient-to-br from-red-800 to-red-600',
      textColor: 'text-white',
    },
    {
      id: 'zara',
      name: 'ZARA',
      tagline: 'Love Your Curves',
      discount: 'New Arrivals',
      color: 'bg-gradient-to-br from-stone-800 to-stone-600',
      textColor: 'text-white',
    },
  ],
  home: [
    {
      id: 'dyson',
      name: 'Dyson',
      tagline: 'Engineering Brilliance',
      discount: 'Up to',
      discountAmount: 10000,
      discountType: 'upto',
      color: 'bg-gradient-to-br from-violet-700 to-violet-500',
      textColor: 'text-white',
    },
    {
      id: 'ikea',
      name: 'IKEA',
      tagline: 'The Wonderful Everyday',
      discount: 'Flat 15% Off',
      color: 'bg-gradient-to-br from-blue-600 to-yellow-400',
      textColor: 'text-white',
    },
    {
      id: 'philips',
      name: 'Philips',
      tagline: 'Innovation and You',
      discount: 'Starting',
      discountAmount: 999,
      discountType: 'starting',
      color: 'bg-gradient-to-br from-sky-700 to-sky-500',
      textColor: 'text-white',
    },
    {
      id: 'prestige',
      name: 'Prestige',
      tagline: "India's Kitchen",
      discount: 'Combo Offers',
      color: 'bg-gradient-to-br from-emerald-700 to-emerald-500',
      textColor: 'text-white',
    },
  ],
  beauty: [
    {
      id: 'loreal',
      name: "L'Oréal",
      tagline: "Because You're Worth It",
      discount: 'Buy 3 for 2',
      color: 'bg-gradient-to-br from-rose-700 to-pink-500',
      textColor: 'text-white',
    },
    {
      id: 'mac',
      name: 'MAC',
      tagline: 'All Ages. All Races. All Genders.',
      discount: 'Up to 25% Off',
      color: 'bg-gradient-to-br from-slate-900 to-slate-700',
      textColor: 'text-white',
    },
    {
      id: 'dyson-beauty',
      name: 'Dyson Beauty',
      tagline: 'Engineered for Hair',
      discount: 'Flat',
      discountAmount: 5000,
      discountType: 'flat',
      color: 'bg-gradient-to-br from-fuchsia-700 to-fuchsia-500',
      textColor: 'text-white',
    },
    {
      id: 'forest-essentials',
      name: 'Forest Essentials',
      tagline: 'Luxurious Ayurveda',
      discount: 'New Collection',
      color: 'bg-gradient-to-br from-green-800 to-green-600',
      textColor: 'text-white',
    },
  ],
  sports: [
    {
      id: 'nike-sport',
      name: 'Nike',
      tagline: 'Just Do It',
      discount: 'Up to 40% Off',
      color: 'bg-gradient-to-br from-orange-700 to-amber-500',
      textColor: 'text-white',
    },
    {
      id: 'decathlon',
      name: 'Decathlon',
      tagline: 'Sport for All',
      discount: 'Starting',
      discountAmount: 199,
      discountType: 'starting',
      color: 'bg-gradient-to-br from-blue-700 to-cyan-500',
      textColor: 'text-white',
    },
    {
      id: 'fitbit',
      name: 'Fitbit',
      tagline: 'Find Your Fit',
      discount: 'Flat',
      discountAmount: 2000,
      discountType: 'flat',
      color: 'bg-gradient-to-br from-teal-700 to-teal-500',
      textColor: 'text-white',
    },
    {
      id: 'puma',
      name: 'Puma',
      tagline: 'Forever Faster',
      discount: 'Min 25% Off',
      color: 'bg-gradient-to-br from-red-700 to-rose-500',
      textColor: 'text-white',
    },
  ],
  toys: [
    {
      id: 'lego',
      name: 'LEGO',
      tagline: 'Build Beyond',
      discount: 'Up to 30% Off',
      color: 'bg-gradient-to-br from-yellow-600 to-red-500',
      textColor: 'text-white',
    },
    {
      id: 'pampers',
      name: 'Pampers',
      tagline: 'Love, Sleep & Play',
      discount: 'Mega Packs Sale',
      color: 'bg-gradient-to-br from-green-600 to-teal-400',
      textColor: 'text-white',
    },
    {
      id: 'chicco',
      name: 'Chicco',
      tagline: "Where There's a Baby",
      discount: 'Flat 20% Off',
      color: 'bg-gradient-to-br from-pink-600 to-rose-400',
      textColor: 'text-white',
    },
    {
      id: 'hasbro',
      name: 'Hasbro',
      tagline: 'Making the World Smile',
      discount: 'Buy 2 Save 15%',
      color: 'bg-gradient-to-br from-blue-600 to-indigo-500',
      textColor: 'text-white',
    },
  ],
  appliances: [
    {
      id: 'lg',
      name: 'LG',
      tagline: "Life's Good",
      discount: 'Up to 40% Off',
      color: 'bg-gradient-to-br from-red-800 to-red-600',
      textColor: 'text-white',
    },
    {
      id: 'whirlpool',
      name: 'Whirlpool',
      tagline: 'Every Day, Care',
      discount: 'Starting',
      discountAmount: 14999,
      discountType: 'starting',
      color: 'bg-gradient-to-br from-blue-800 to-sky-600',
      textColor: 'text-white',
    },
    {
      id: 'daikin',
      name: 'Daikin',
      tagline: 'Perfecting the Air',
      discount: 'Summer Sale',
      color: 'bg-gradient-to-br from-cyan-700 to-cyan-500',
      textColor: 'text-white',
    },
    {
      id: 'samsung-appliance',
      name: 'Samsung',
      tagline: 'Innovation First',
      discount: 'EMI from',
      discountAmount: 999,
      discountType: 'emi',
      color: 'bg-gradient-to-br from-slate-800 to-blue-700',
      textColor: 'text-white',
    },
  ],
};

// ── Featured / Trending ────────────────────────────────────────────────────

export const TRENDING_PRODUCTS: HomeProduct[] = [
  {
    id: '3e146924-4876-4de0-967e-19e836208bb6',
    title: 'Apple Watch Ultra 2 – Titanium Case',
    brand: 'Apple',
    price: 89900,
    mrp: 89900,
    rating: 4.9,
    reviews: '2.8k',
    badge: 'TRENDING',
    badgeColor: 'bg-violet-600',
    icon: 'Watch',
    category: 'watches',
    delivery: '2-3 days',
  },
  {
    id: '6b361b3e-426e-4027-9f42-e6273128bd99',
    title: 'Nothing Phone (2a) Plus – Grey',
    brand: 'Nothing',
    price: 27999,
    mrp: 29999,
    rating: 4.4,
    reviews: '3.5k',
    badge: 'TRENDING',
    badgeColor: 'bg-violet-600',
    icon: 'Smartphone',
    category: 'mobiles-tablets',
    delivery: '2-3 days',
  },
  {
    id: '45627fbd-6661-4ddc-9239-0bf354dec632',
    title: 'boAt Airdopes 141 TWS Earbuds',
    brand: 'boAt',
    price: 1099,
    mrp: 4490,
    rating: 4.1,
    reviews: '145k',
    badge: 'TRENDING',
    badgeColor: 'bg-violet-600',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: 'd3f12b49-fed6-4544-a889-99a874b823c2',
    title: 'Amazon Fire TV Stick 4K Max (2nd Gen)',
    brand: 'Amazon',
    price: 4999,
    mrp: 7999,
    rating: 4.5,
    reviews: '62k',
    badge: 'TRENDING',
    badgeColor: 'bg-violet-600',
    icon: 'Tv',
    category: 'appliances',
    delivery: 'Tomorrow',
  },
  {
    id: '8e8af2a2-867c-426e-9e54-0a9144ab1e1b',
    title: 'Kindle Paperwhite (16GB) – Black',
    brand: 'Amazon',
    price: 14999,
    mrp: 16999,
    rating: 4.7,
    reviews: '18k',
    badge: 'TRENDING',
    badgeColor: 'bg-violet-600',
    icon: 'BookOpen',
    category: 'books',
    delivery: '2-3 days',
  },
];

// ── Deals of the Day ───────────────────────────────────────────────────────

export const DEALS_OF_DAY: HomeProduct[] = [
  {
    id: 'b5361818-0249-48da-8624-cc95b16864f2',
    title: 'Samsung Galaxy Buds2 Pro – Graphite',
    brand: 'Samsung',
    price: 9999,
    mrp: 17999,
    rating: 4.5,
    reviews: '6.1k',
    badge: '44% OFF',
    badgeColor: 'bg-red-600',
    icon: 'Headphones',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
  {
    id: '94d4ee59-cb12-4402-bd19-488a13261d4b',
    title: 'Instant Pot Duo 7-in-1 (6 Quart)',
    brand: 'Instant Pot',
    price: 6999,
    mrp: 13999,
    rating: 4.6,
    reviews: '21k',
    badge: '50% OFF',
    badgeColor: 'bg-red-600',
    icon: 'Sofa',
    category: 'home-kitchen',
    delivery: '2-3 days',
  },
  {
    id: 'dfcfbeaa-85ee-4699-9a86-2bbf4d81b423',
    title: 'Crocs Classic Clog – Army Green',
    brand: 'Crocs',
    price: 2697,
    mrp: 4495,
    rating: 4.4,
    reviews: '35k',
    badge: '40% OFF',
    badgeColor: 'bg-red-600',
    icon: 'Shirt',
    category: 'footwear',
    delivery: '2-3 days',
  },
  {
    id: 'f4ea9dfb-c596-4834-bca8-a594658f97c7',
    title: 'Noise ColorFit Ultra 3 Smartwatch',
    brand: 'Noise',
    price: 2999,
    mrp: 6999,
    rating: 4.2,
    reviews: '8.9k',
    badge: '57% OFF',
    badgeColor: 'bg-red-600',
    icon: 'Watch',
    category: 'watches',
    delivery: 'Tomorrow',
  },
  {
    id: 'ba3500c9-1f62-4e68-a718-52b255c9f78f',
    title: 'boAt Stone 1200 14W Speaker',
    brand: 'boAt',
    price: 1999,
    mrp: 3990,
    rating: 4.3,
    reviews: '18k',
    badge: '50% OFF',
    badgeColor: 'bg-red-600',
    icon: 'Speaker',
    category: 'electronics',
    delivery: 'Tomorrow',
  },
];

// ── Trust Badges ───────────────────────────────────────────────────────────

// Tagged by market, like the banners below. Three of these are claims about a
// specific country's payment rails and tax regime — "GPay, PhonePe, Paytm",
// "India-wide" delivery and a "GST Invoice" are all meaningless in Doha, and a
// storefront that advertises a tax document it cannot issue is worse than one
// that stays quiet. The free-delivery threshold is deliberately per-market too:
// it is a bare number rendered through the active currency formatter, so a
// single value would read as 499 riyals in Qatar and 499 rupees in India.
// ── Hero Banners ───────────────────────────────────────────────────────────
//
// Every entry below is tagged with the markets it belongs to. A festival sale,
// a national holiday and a city delivery promise are all market-specific
// claims; running them everywhere advertises offers that cannot be honoured.

export const HERO_BANNERS: (RegionTargeted & {
  id: string;
  tag: string;
  headline: string;
  cta: string;
  gradient: string;
  ctaHref: string;
  startingPrice?: number;
})[] = [
  // ── Qatar & the Gulf ──
  {
    id: 'qa-national-day',
    regions: ['QA'],
    tag: '🇶🇦 QATAR NATIONAL DAY',
    headline: 'Celebrate Qatar\nUp to 60% Off Sitewide',
    cta: 'Shop Now',
    gradient: 'from-red-900 via-slate-900 to-red-800',
    ctaHref: '/marketplace/offers',
  },
  {
    id: 'gulf-eid',
    regions: ['QA', 'AE', 'SA', 'BH', 'KW', 'OM'],
    tag: '🌙 EID MUBARAK',
    headline: 'Eid Gifting Season\nElectronics, Fashion & Home',
    cta: 'Grab Deals',
    gradient: 'from-emerald-800 via-teal-900 to-slate-900',
    ctaHref: '/marketplace/category/electronics',
  },
  {
    id: 'gulf-summer',
    regions: ['QA', 'AE', 'SA', 'BH', 'KW', 'OM'],
    tag: '☀️ SUMMER ESCAPE',
    headline: 'Beat the Gulf Summer\nCooling, Travel & Indoor Living',
    cta: 'Shop Now',
    gradient: 'from-sky-700 via-cyan-800 to-blue-900',
    ctaHref: '/marketplace/category/appliances',
  },

  // ── India ──
  {
    id: 'big-billion',
    regions: ['IN'],
    tag: '🎉 BIG BILLION DAYS',
    headline: "India's Biggest Sale\nUp to 80% Off Everything",
    cta: 'Shop Now',
    gradient: 'from-orange-600 via-red-700 to-orange-900',
    ctaHref: '/marketplace/offers',
  },
  {
    id: 'diwali-sale',
    regions: ['IN'],
    tag: '🪔 DIWALI DHOOM SALE',
    headline: 'Festive Season Offers\nElectronics, Fashion & More',
    cta: 'Grab Deals',
    gradient: 'from-yellow-700 via-orange-800 to-red-900',
    ctaHref: '/marketplace/category/electronics',
  },
  {
    id: 'republic-day',
    regions: ['IN'],
    tag: '🇮🇳 REPUBLIC DAY SALE',
    headline: 'Proud to be Indian\nMin 26% Off Sitewide',
    cta: 'Shop India',
    gradient: 'from-green-800 via-slate-900 to-orange-900',
    ctaHref: '/marketplace/offers',
  },
  {
    id: 'made-in-india',
    regions: ['IN'],
    tag: '🏭 ATMANIRBHAR BHARAT',
    headline: 'Made in India\nTop Indian Brands',
    startingPrice: 99,
    cta: 'Explore Now',
    gradient: 'from-orange-700 via-amber-800 to-green-900',
    ctaHref: '/marketplace/category-list',
  },
  {
    id: 'ipl-sale',
    regions: ['IN'],
    tag: '🏏 IPL SHOPPING FEST',
    headline: 'Hit a Six on Savings\nCricket & Sports Up to 50% Off',
    cta: 'Play & Save',
    gradient: 'from-blue-900 via-indigo-900 to-violet-900',
    ctaHref: '/marketplace/category/sports',
  },

  // ── Every market ──
  {
    id: 'new-arrivals-global',
    tag: '✨ JUST LANDED',
    headline: 'New Arrivals\nFresh Picks Across Every Category',
    cta: 'Explore',
    gradient: 'from-slate-800 via-indigo-900 to-slate-900',
    ctaHref: '/marketplace/new-arrivals',
  },
];

// ── Seasonal Campaign Banners ──────────────────────────────────────────────

export const CAMPAIGN_BANNERS: CampaignBanner[] = [
  // ── Qatar & the Gulf ──
  {
    id: 'qa-himyan-offer',
    regions: ['QA'],
    tag: '💳 HIMYAN CASHBACK',
    headline: 'Pay with Himyan & save instantly',
    subheadline: 'Instant cashback on every Himyan and NAPS debit card payment.',
    cta: 'Claim Offer',
    ctaHref: '/marketplace/offers',
    gradient: 'from-purple-600 via-violet-600 to-indigo-600',
    icon: 'Smartphone',
  },
  {
    id: 'gulf-cooling',
    regions: ['QA', 'AE', 'SA', 'BH', 'KW', 'OM'],
    tag: '☀️ SUMMER COOL-OFF',
    headline: 'Beat the Gulf heat',
    subheadline: 'Air conditioners, coolers and fans — up to 50% off with free installation.',
    cta: 'Shop Now',
    ctaHref: '/marketplace/category/appliances',
    gradient: 'from-sky-500 via-cyan-500 to-teal-500',
    icon: 'Sun',
  },
  {
    id: 'gulf-back-to-school',
    regions: ['QA', 'AE', 'SA', 'BH', 'KW', 'OM'],
    tag: '✏️ BACK TO SCHOOL',
    headline: 'Ready for the new term',
    subheadline: 'Stationery, bags and school essentials — starting',
    startingPrice: 15,
    cta: 'Shop Essentials',
    ctaHref: '/marketplace/category/books',
    gradient: 'from-blue-600 via-indigo-600 to-violet-600',
    icon: 'GraduationCap',
  },

  // ── India ──
  {
    id: 'upi-offer',
    regions: ['IN'],
    tag: '💳 UPI CASHBACK OFFER',
    headline: 'Pay with UPI & Save ₹150',
    subheadline: 'Use GPay, PhonePe, Paytm or any UPI app — get instant cashback!',
    cta: 'Claim Offer',
    ctaHref: '/marketplace/offers',
    gradient: 'from-purple-600 via-violet-600 to-indigo-600',
    icon: 'Smartphone',
  },
  {
    id: 'summer-ac-sale',
    regions: ['IN'],
    tag: '☀️ SUMMER COOL-OFF',
    headline: 'Beat the Indian Heat',
    subheadline: 'ACs, Air Coolers, Fans & More — Up to 50% Off + Free Installation',
    cta: 'Shop Now',
    ctaHref: '/marketplace/category/appliances',
    gradient: 'from-sky-500 via-cyan-500 to-teal-500',
    icon: 'Sun',
  },
  {
    id: 'back-to-school',
    regions: ['IN'],
    tag: '✏️ BACK TO SCHOOL',
    headline: 'Padhai Ki Tayari',
    subheadline: 'Stationery, School Bags, NCERT Books — Starting',
    startingPrice: 49,
    cta: 'Shop Essentials',
    ctaHref: '/marketplace/category/books',
    gradient: 'from-blue-600 via-indigo-600 to-violet-600',
    icon: 'GraduationCap',
  },

  // ── Every market ──
  {
    id: 'emi-no-cost',
    tag: '🏦 PAY IN INSTALMENTS',
    headline: 'Buy Now, Pay Later',
    subheadline: 'Interest-free instalments on major credit cards — 3, 6, 9 and 12 month plans.',
    cta: 'Check Offers',
    ctaHref: '/marketplace/offers',
    gradient: 'from-emerald-600 via-teal-600 to-cyan-600',
    icon: 'Award',
  },
];

// ── City Delivery Banners ──────────────────────────────────────────────────
//
// City-level targeting, the way Amazon and Flipkart do it. Scoped by market so
// a Doha shopper is not promised same-day delivery in Gurugram.

export const COUNTRY_BANNERS: CountryBanner[] = [
  // ── Qatar ──
  {
    id: 'doha',
    regions: ['QA'],
    country: 'Doha',
    flag: '🏙️',
    headline: 'Shop in Doha',
    subtitle: 'Same-day delivery across West Bay, Al Sadd and Msheireb',
    gradient: 'from-red-800 via-rose-700 to-slate-800',
    href: '/marketplace?city=doha',
  },
  {
    id: 'al-rayyan',
    regions: ['QA'],
    country: 'Al Rayyan',
    flag: '🕌',
    headline: 'Al Rayyan Deals',
    subtitle: 'Next-day delivery to Al Rayyan, Muaither and Al Gharrafa',
    gradient: 'from-emerald-800 via-teal-700 to-slate-800',
    href: '/marketplace?city=al-rayyan',
  },
  {
    id: 'al-wakrah',
    regions: ['QA'],
    country: 'Al Wakrah',
    flag: '⚓',
    headline: 'Al Wakrah & Al Wukair',
    subtitle: 'Fast delivery across the southern municipalities',
    gradient: 'from-blue-800 via-cyan-700 to-slate-800',
    href: '/marketplace?city=al-wakrah',
  },
  {
    id: 'qatar-wide',
    regions: ['QA'],
    country: 'All Qatar',
    flag: '🇶🇦',
    headline: 'Nationwide Delivery',
    subtitle: 'We deliver to every zone across all municipalities',
    gradient: 'from-red-700 via-red-800 to-slate-900',
    href: '/marketplace',
  },

  // ── India ──
  {
    id: 'delhi',
    regions: ['IN'],
    country: 'Delhi NCR',
    flag: '🏙️',
    headline: 'Shop in Delhi NCR',
    subtitle: 'Same-day delivery in Delhi, Noida, Gurugram',
    gradient: 'from-orange-600 via-amber-500 to-red-600',
    href: '/marketplace?city=delhi',
  },
  {
    id: 'mumbai',
    regions: ['IN'],
    country: 'Mumbai',
    flag: '🌊',
    headline: 'Mumbai ke Best Deals',
    subtitle: 'Express delivery across Mumbai & Thane',
    gradient: 'from-blue-700 via-teal-600 to-emerald-600',
    href: '/marketplace?city=mumbai',
  },
  {
    id: 'bengaluru',
    regions: ['IN'],
    country: 'Bengaluru',
    flag: '🌿',
    headline: 'Bengaluru Tech Offers',
    subtitle: 'Next-day delivery to Koramangala, Whitefield, HSR',
    gradient: 'from-green-700 via-emerald-600 to-teal-600',
    href: '/marketplace?city=bengaluru',
  },
  {
    id: 'hyderabad',
    regions: ['IN'],
    country: 'Hyderabad',
    flag: '🏰',
    headline: 'Hyderabad ka Mela',
    subtitle: 'Fast delivery to HITEC City, Banjara Hills',
    gradient: 'from-purple-700 via-indigo-600 to-blue-600',
    href: '/marketplace?city=hyderabad',
  },
  {
    id: 'india-wide',
    regions: ['IN'],
    country: 'All India',
    flag: '🇮🇳',
    headline: 'Pan-India Delivery',
    subtitle: 'We deliver to 26,000+ PIN codes across India',
    gradient: 'from-orange-500 via-orange-600 to-green-700',
    href: '/marketplace',
  },

  // ── UAE ──
  {
    id: 'dubai',
    regions: ['AE'],
    country: 'Dubai',
    flag: '🏗️',
    headline: 'Shop in Dubai',
    subtitle: 'Same-day delivery across Downtown, Marina and Deira',
    gradient: 'from-amber-700 via-orange-700 to-slate-800',
    href: '/marketplace?city=dubai',
  },
  {
    id: 'abu-dhabi',
    regions: ['AE'],
    country: 'Abu Dhabi',
    flag: '🕌',
    headline: 'Abu Dhabi Offers',
    subtitle: 'Next-day delivery across the capital',
    gradient: 'from-emerald-800 via-green-700 to-slate-800',
    href: '/marketplace?city=abu-dhabi',
  },
];

// ── Homepage FAQ for AEO ───────────────────────────────────────────────────
//
// Search engines index these answers, so a wrong one is worse than none: an
// answer promising GST invoices and PIN-code serviceability to a Qatari shopper
// describes a service they cannot use and a tax that does not exist there.

// ── Helper Functions ───────────────────────────────────────────────────────

// ── Auto-enrich all products with images from curated image map ────────────

function enrichProducts(products: HomeProduct[]): HomeProduct[] {
  return products.map((p) => ({
    ...p,
    imageUrl: p.imageUrl || getProductImage(p.id),
  }));
}

// Enrich all exported arrays in-place at module load
[
  FLASH_DEALS,
  ELECTRONICS_PRODUCTS,
  FASHION_PRODUCTS,
  HOME_PRODUCTS,
  BEAUTY_PRODUCTS,
  SPORTS_PRODUCTS,
  TOYS_PRODUCTS,
  APPLIANCES_PRODUCTS,
  TRENDING_PRODUCTS,
  DEALS_OF_DAY,
  NEW_ARRIVALS,
  BEST_SELLERS,
  RECOMMENDED,
  SPONSORED_PRODUCTS,
].forEach((arr) => {
  const enriched = enrichProducts(arr);
  arr.splice(0, arr.length, ...enriched);
});

// Enrich categories with thumbnails
CATEGORIES.forEach((cat) => {
  const img = getCategoryImage(cat.id);
  if (img) cat.imageUrl = img;
});
