import type { TranslationKeys } from '../types';
import en from './en';

/**
 * Hindi (हिन्दी) translation — India
 * Spreads from English base and overrides all user-facing keys.
 */
const hi: TranslationKeys = {
  ...en,
  common: { ...en.common, appName: 'कार्टसीक', tagline: 'अंतिम सुपर ऐप', searchPlaceholder: 'उत्पाद, किराना, रेस्तरां खोजें...', searchIn: '{{city}} में खोजें…', loading: 'लोड हो रहा है…', detecting: 'पता लगा रहे हैं…', viewAll: 'सभी देखें', seeAll: 'सभी देखें', learnMore: 'अधिक जानें', back: 'वापस', next: 'अगला', cancel: 'रद्द करें', save: 'सहेजें', delete: 'हटाएं', edit: 'संपादित करें', close: 'बंद करें', confirm: 'पुष्टि करें', yes: 'हाँ', no: 'नहीं', ok: 'ठीक', error: 'त्रुटि', success: 'सफल', warning: 'चेतावनी', retry: 'पुनः प्रयास', noResults: 'कोई परिणाम नहीं मिला', selectRegion: 'क्षेत्र चुनें', language: 'भाषा', country: 'देश', currency: 'मुद्रा', settings: 'सेटिंग्स', logout: 'लॉग आउट', login: 'लॉग इन', signUp: 'साइन अप', signOut: 'साइन आउट', or: 'या', and: 'और', of: 'का', all: 'सभी', none: 'कोई नहीं', filter: 'फ़िल्टर', sort: 'क्रमबद्ध', apply: 'लागू करें', reset: 'रीसेट', more: 'अधिक', less: 'कम', showMore: 'और दिखाएं', showLess: 'कम दिखाएं', minutes: 'मिनट', hours: 'घंटे', days: 'दिन', today: 'आज', yesterday: 'कल', justNow: 'अभी', ago: 'पहले', min: 'मि', hr: 'घं', km: 'किमी', mi: 'मील', promoted: 'प्रमोटेड', featured: 'फीचर्ड', new: 'नया', hot: 'हॉट', popular: 'लोकप्रिय', trending: 'ट्रेंडिंग', topRated: 'शीर्ष रेटेड', bestSeller: 'सबसे ज़्यादा बिकने वाला', freeDelivery: 'मुफ्त डिलीवरी', orderNow: 'अभी ऑर्डर करें', shopNow: 'अभी खरीदें', bookNow: 'अभी बुक करें', exploreNow: 'अभी एक्सप्लोर करें', getStarted: 'शुरू करें', continueText: 'जारी रखें', submit: 'जमा करें', update: 'अपडेट', remove: 'हटाएं', add: 'जोड़ें', share: 'शेयर', copy: 'कॉपी', download: 'डाउनलोड', upload: 'अपलोड', switchLanguage: 'भाषा बदलें', switchCountry: 'देश बदलें', rtl: 'दाएं से बाएं', ltr: 'बाएं से दाएं', darkMode: 'डार्क मोड', lightMode: 'लाइट मोड', poweredBy: 'कार्टसीक द्वारा संचालित', allRightsReserved: 'सर्वाधिकार सुरक्षित।', termsOfService: 'सेवा की शर्तें', privacyPolicy: 'गोपनीयता नीति', helpCenter: 'सहायता केंद्र', contactUs: 'संपर्क करें' },
  nav: { ...en.nav, home: 'होम', shop: 'दुकान', orders: 'ऑर्डर', wishlist: 'विशलिस्ट', profile: 'प्रोफ़ाइल', cart: 'कार्ट', notifications: 'सूचनाएं', search: 'खोज', menu: 'मेनू', marketplace: 'मार्केटप्लेस', grocery: 'किराना', restaurant: 'रेस्तरां', foodDelivery: 'फूड डिलीवरी', pharmacy: 'फार्मेसी', doctor: 'डॉक्टर', taxi: 'टैक्सी', wallet: 'वॉलेट', rewards: 'पुरस्कार', loyalty: 'लॉयल्टी', support: 'सहायता', helpSupport: 'सहायता और समर्थन', sellerPortal: 'विक्रेता पोर्टल', driverPortal: 'ड्राइवर / डिलीवरी पोर्टल', franchise: 'फ्रैंचाइज़', adminConsole: 'एडमिन कंसोल' },
  home: { ...en.home, walletLabel: 'वॉलेट', walletTopUp: 'टॉप अप करें', loyaltyLabel: 'लॉयल्टी', loyaltyPoints: '{{points}} अंक', loyaltyValue: '≈ {{currency}} {{value}} मूल्य', ourServices: 'हमारी सेवाएं', recentOrders: 'हाल के ऑर्डर', trendingNow: 'अभी ट्रेंडिंग', nearbyStores: 'आस-पास के किराना स्टोर', popularBrands: 'लोकप्रिय ब्रांड', premiumRestaurants: 'प्रीमियम रेस्तरां', premiumRestaurantsDesc: 'आपके पास सर्वोत्तम डाइनिंग अनुभव', browseAllRestaurants: 'सभी रेस्तरां देखें', trackOrder: 'ऑर्डर ट्रैक करें', liveUpdates: 'लाइव अपडेट', getHelp: 'सहायता प्राप्त करें', support247: '24/7 सहायता', avgDelivery: 'औसत डिलीवरी', appRating: 'ऐप रेटिंग', securePay: 'सुरक्षित भुगतान', delivery: 'डिलीवरी', takeaway: 'टेकअवे', dineIn: 'डाइन-इन', bookTable: 'टेबल बुक करें', forTwo: 'दो के लिए', quickActions: 'त्वरित कार्य', storesFound: '{{count}} स्टोर मिले', storesDeliveringNow: 'अभी आपके स्थान पर डिलीवर करने वाले स्टोर' },
  auth: { ...en.auth, loginTitle: 'वापस स्वागत है', signUpTitle: 'खाता बनाएं', emailLabel: 'ईमेल पता', passwordLabel: 'पासवर्ड', forgotPassword: 'पासवर्ड भूल गए?', rememberMe: 'मुझे याद रखें', noAccount: 'खाता नहीं है?', hasAccount: 'पहले से खाता है?', createAccount: 'खाता बनाएं', welcomeBack: 'वापस स्वागत है!', nameLabel: 'पूरा नाम', phoneLabel: 'फोन नंबर', confirmPassword: 'पासवर्ड की पुष्टि करें', agreeTerms: 'मैं सेवा की शर्तों और गोपनीयता नीति से सहमत हूं',
    signIn: 'साइन इन करें', signInSubtitle: 'अपने ऑर्डर, वॉलेट और सभी सुपर ऐप सेवाओं तक पहुंचने के लिए साइन इन करें।', signUpHeadline: 'सुपर ऐप से जुड़ें', signUpSubtitle: 'अपना मुफ़्त खाता बनाएं और शॉपिंग, फ़ूड डिलीवरी, राइड्स और बहुत कुछ पाएं।', createOneFree: 'मुफ़्त खाता बनाएं', orSignUpWith: 'या इससे साइन अप करें', phoneOtp: 'फोन ओटीपी', optional: '(वैकल्पिक)', agreeToThe: 'मैं सहमत हूं', showPassword: 'पासवर्ड दिखाएं', hidePassword: 'पासवर्ड छिपाएं', emailPlaceholder: 'you@example.com', namePlaceholder: 'राहुल शर्मा', passwordMinPlaceholder: 'कम से कम 8 अक्षर', phonePlaceholder: '{{code}} XXXX XXXX',
    forgotPasswordTitle: 'पासवर्ड भूल गए', forgotPasswordSubtitle: 'अपने खाते से जुड़ा ईमेल पता दर्ज करें, हम आपको पासवर्ड रीसेट करने का लिंक भेजेंगे।', resetHeadline: 'अपना पासवर्ड रीसेट करें', resetHeadlineBody: 'चिंता न करें — हम आपको खाते में वापस आने के लिए एक सुरक्षित लिंक ईमेल करेंगे।', sendResetLink: 'रीसेट लिंक भेजें', resetLinkSent: 'अपना ईमेल देखें', resetLinkSentBody: 'यदि {{email}} के लिए खाता मौजूद है, तो हमने पासवर्ड रीसेट करने का लिंक भेज दिया है। यह एक बार उपयोग हो सकता है और 30 मिनट में समाप्त हो जाता है।', notInInbox: 'इनबॉक्स में नहीं मिला? स्पैम फ़ोल्डर देखें, या', tryDifferentAddress: 'दूसरा पता आज़माएं', featSingleUseLink: 'एक बार उपयोग होने वाला लिंक, 30 मिनट तक वैध', featEncryptedReset: '256-बिट एन्क्रिप्टेड पासवर्ड रीसेट', backToSignIn: 'साइन इन पर वापस जाएं', resetPasswordTitle: 'नया पासवर्ड सेट करें', resetPasswordSubtitle: 'ऐसा पासवर्ड चुनें जो आपने पहले उपयोग न किया हो।', newPassword: 'नया पासवर्ड', updatePassword: 'पासवर्ड रीसेट करें', passwordUpdated: 'पासवर्ड रीसेट हो गया', passwordUpdatedBody: 'आपका पासवर्ड रीसेट कर दिया गया है। अब आप अपने नए पासवर्ड से साइन इन कर सकते हैं।', creatingPasswordFor: '{{email}} के लिए नया पासवर्ड बनाया जा रहा है', createNewPasswordHeadline: 'नया पासवर्ड बनाएं', createNewPasswordBody: 'अपना खाता सुरक्षित रखने के लिए मज़बूत पासवर्ड चुनें।', featMixCharacters: 'अक्षरों, अंकों और चिह्नों का मिश्रण उपयोग करें', featNeverReuse: 'अलग-अलग साइटों पर एक ही पासवर्ड दोबारा न लगाएं', passwordsMatch: 'पासवर्ड मेल खाते हैं', pwStrengthWeak: 'कमज़ोर', pwStrengthFair: 'ठीक-ठाक', pwStrengthGood: 'अच्छा', pwStrengthStrong: 'मज़बूत', pwCheckLength: 'कम से कम 8 अक्षर', pwCheckUpper: 'बड़ा अक्षर', pwCheckLower: 'छोटा अक्षर', pwCheckNumber: 'अंक', pwCheckSpecial: 'विशेष चिह्न',
    featShopCategories: '7 सेवा श्रेणियों में खरीदारी करें', featBookServices: 'होटल, रेस्तरां, राइड्स और बहुत कुछ बुक करें', featSecurePayments: '256-बिट एन्क्रिप्शन के साथ सुरक्षित भुगतान', featOneAccount: 'सभी 7 सेवाओं के लिए एक खाता', featWelcomeBonus: 'स्वागत बोनस के रूप में 100 लॉयल्टी पॉइंट पाएं', featDataProtected: 'आपका डेटा उच्च-स्तरीय सुरक्षा से सुरक्षित है',
    errFillAllFields: 'कृपया सभी फ़ील्ड भरें।', errFillAllRequired: 'कृपया सभी आवश्यक फ़ील्ड भरें।', errEnterEmail: 'कृपया अपना ईमेल पता दर्ज करें।', errInvalidEmail: 'कृपया वैध ईमेल पता दर्ज करें।', errResetLinkFailed: 'हम रीसेट लिंक नहीं भेज सके। कृपया थोड़ी देर बाद पुनः प्रयास करें।', errPasswordRule: 'पासवर्ड 8–128 अक्षरों का होना चाहिए और इसमें एक बड़ा अक्षर, एक छोटा अक्षर, एक अंक और एक विशेष चिह्न (@$!%*?&^#) होना चाहिए।', errPasswordMismatch: 'दोनों पासवर्ड मेल नहीं खाते।', errMustAgreeTerms: 'आपको नियम और शर्तों से सहमत होना होगा।', errCheckEmailPassword: 'कृपया अपना ईमेल और पासवर्ड जांचें।', errCheckDetails: 'कृपया दर्ज की गई जानकारी जांचें।', errEmailExists: 'इस ईमेल से खाता पहले से मौजूद है। इसके बजाय साइन इन करें।', errSignInUnreachable: 'हम साइन-इन सेवा तक नहीं पहुंच सके। कृपया थोड़ी देर बाद पुनः प्रयास करें।', errSignInUnreachableNetwork: 'हम साइन-इन सेवा तक नहीं पहुंच सके। अपना कनेक्शन जांचें और पुनः प्रयास करें।', errSignUpUnreachable: 'हम साइन-अप सेवा तक नहीं पहुंच सके। कृपया थोड़ी देर बाद पुनः प्रयास करें।', errSignUpUnreachableNetwork: 'हम साइन-अप सेवा तक नहीं पहुंच सके। अपना कनेक्शन जांचें और पुनः प्रयास करें।', errSignInFailed: 'साइन इन विफल रहा। कृपया पुनः प्रयास करें।', errSignUpFailed: 'साइन अप विफल रहा। कृपया पुनः प्रयास करें।', errResetFailed: 'हम आपका पासवर्ड रीसेट नहीं कर सके। कृपया नया लिंक मांगें।', errResetLinkInvalid: 'यह रीसेट लिंक अमान्य है या समाप्त हो चुका है।' },
  account: { ...en.account, myAccount: 'मेरा खाता', ordersBookings: 'ऑर्डर और बुकिंग', savedAddresses: 'सहेजे गए पते', securitySettings: 'सुरक्षा सेटिंग्स', loyaltyPoints: 'लॉयल्टी पॉइंट्स', paymentMethods: 'भुगतान विधियां', preferences: 'प्राथमिकताएं', personalInfo: 'व्यक्तिगत जानकारी', changePassword: 'पासवर्ड बदलें', manageAddresses: 'पते प्रबंधित करें', orderHistory: 'ऑर्डर इतिहास', activeOrders: 'सक्रिय ऑर्डर', completedOrders: 'पूर्ण ऑर्डर', cancelledOrders: 'रद्द ऑर्डर' },
  grocery: { ...en.grocery, title: 'किराना', freshGroceries: 'ताज़ा किराना', deliveredIn: '{{time}} में डिलीवरी', nearbyStores: 'आस-पास के स्टोर', shopByBrand: 'ब्रांड से खरीदें', trendingStores: 'ट्रेंडिंग स्टोर', todaysDeals: 'आज के सौदे', allBrands: 'सभी ब्रांड', lightningFast: 'बिजली की तेज़ी से', orderDescription: 'अपने पसंदीदा स्थानीय स्टोर से ताज़े फल, सब्ज़ियां, मांस और दैनिक आवश्यकताएं ऑर्डर करें।', mostPopular: 'सबसे लोकप्रिय', risingFast: 'तेज़ी से बढ़ रहा', fastestDelivery: 'सबसे तेज़ डिलीवरी', ordersThisWeek: 'इस हफ्ते {{count}} ऑर्डर' },
  food: { ...en.food, title: 'फूड डिलीवरी', restaurants: 'रेस्तरां', cuisines: 'व्यंजन', addToCart: 'कार्ट में डालें', viewMenu: 'मेनू देखें', deliveryTime: 'डिलीवरी समय', costForTwo: 'दो के लिए कीमत', bestSellers: 'सबसे ज़्यादा बिकने वाले', recommended: 'अनुशंसित', pureVeg: 'शुद्ध शाकाहारी', nonVeg: 'मांसाहारी', tableBooking: 'टेबल बुकिंग' },
  pharmacy: { ...en.pharmacy, title: 'फार्मेसी', orderMedicine: 'दवा ऑर्डर करें', uploadPrescription: 'प्रिस्क्रिप्शन अपलोड करें', searchMedicine: 'दवा खोजें', addToCart: 'कार्ट में डालें', dosage: 'खुराक', quantity: 'मात्रा', manufacturer: 'निर्माता', expiryDate: 'समाप्ति तिथि', healthProducts: 'स्वास्थ्य उत्पाद', wellness: 'वेलनेस' },
  doctor: { ...en.doctor, title: 'डॉक्टर', findDoctor: 'डॉक्टर खोजें', bookAppointment: 'अपॉइंटमेंट बुक करें', specialization: 'विशेषज्ञता', experience: 'अनुभव', consultationFee: 'परामर्श शुल्क', availability: 'उपलब्धता', onlineConsultation: 'ऑनलाइन परामर्श', inClinic: 'क्लिनिक में', ratings: 'रेटिंग', patients: 'मरीज़', years: 'वर्ष' },
  taxi: { ...en.taxi, title: 'टैक्सी', bookRide: 'राइड बुक करें', whereToGo: 'कहाँ जाना है?', pickupLocation: 'पिकअप लोकेशन', dropLocation: 'ड्रॉप लोकेशन', estimatedFare: 'अनुमानित किराया', sedan: 'सेडान', suv: 'एसयूवी', auto: 'ऑटो', bike: 'बाइक', premium: 'प्रीमियम', driverArriving: 'ड्राइवर आ रहा है', rideCompleted: 'राइड पूरी हुई', rateYourRide: 'अपनी राइड रेट करें', currentLocation: 'वर्तमान स्थान' },
  cart: { ...en.cart, myCart: 'मेरा कार्ट', emptyCart: 'आपका कार्ट खाली है', subtotal: 'उप-योग', deliveryFee: 'डिलीवरी शुल्क', discount: 'छूट', total: 'कुल', tax: 'कर', taxIncluded: 'कर शामिल', checkout: 'चेकआउट', continueShopping: 'खरीदारी जारी रखें', placeOrder: 'ऑर्डर प्लेस करें', orderConfirmed: 'ऑर्डर कन्फर्म!', payNow: 'अभी भुगतान करें', cashOnDelivery: 'कैश ऑन डिलीवरी', wallet: 'वॉलेट' },
  orders: { ...en.orders, myOrders: 'मेरे ऑर्डर', orderDetails: 'ऑर्डर विवरण', delivered: 'डिलीवर हो गया', cancelled: 'रद्द', trackOrder: 'ऑर्डर ट्रैक करें', reorder: 'दोबारा ऑर्डर', cancelOrder: 'ऑर्डर रद्द करें', onTheWay: 'रास्ते में', status: 'स्थिति' },
  admin: { ...en.admin, dashboard: 'डैशबोर्ड', users: 'उपयोगकर्ता', sellers: 'विक्रेता', partners: 'साझेदार', analytics: 'एनालिटिक्स', content: 'सामग्री', commissions: 'कमीशन', refunds: 'धनवापसी', reports: 'रिपोर्ट', settings: 'सेटिंग्स', configure: 'कॉन्फ़िगर', totalEarned: 'कुल कमाई', saveConfiguration: 'कॉन्फ़िगरेशन सहेजें' },
  footer: { ...en.footer, about: 'हमारे बारे में', aboutDescription: 'अफ्रीका, एशिया और मध्य पूर्व में खरीदारी, भोजन, स्वास्थ्य और सवारी के लिए आपका ऑल-इन-वन सुपर ऐप।', shopAndOrder: 'खरीदें और ऑर्डर करें', services: 'सेवाएं', partnerWithUs: 'हमारे साथ साझेदारी', supportLegal: 'सहायता और कानूनी' },
  notifications: { ...en.notifications, title: 'सूचनाएं', markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें', noNotifications: 'अभी तक कोई सूचना नहीं' },
  promos: { ...en.promos, newUser: '🚀 नया उपयोगकर्ता', flashSale: '⚡ फ्लैश सेल', healthDeal: '💊 हेल्थ डील', flat50Off: 'फ्लैट 50% छूट', freeDelivery: 'मुफ्त डिलीवरी', todayOnly: 'केवल आज।' },
  errors: { ...en.errors, somethingWentWrong: 'कुछ गलत हो गया', pageNotFound: 'पृष्ठ नहीं मिला', tryAgain: 'पुनः प्रयास करें', goBack: 'वापस जाएं', goHome: 'होम पर जाएं' },
};

export default hi;
