/**
 * Renders infra/docker/compose.services.yml from services.yaml.
 *
 * The root docker-compose.yml has promised this file since phase 3 and it has
 * never existed: not the gateway, not one of the 17 core services, not one of
 * the 8 module backends, not the console was defined in Compose (AUD2-067).
 * Hand-writing 35 services is how the ports, the health routes and the
 * dependency lists drift from the registry, so it is generated and
 * `npm run registry:check` fails when it is stale.
 *
 * Addressing: inside kartseek-network, infrastructure answers to its compose
 * service name — postgres, redis, kafka, mongodb, elasticsearch — and a
 * service's peers answer to their container's service name. Nothing here may
 * say localhost: that is the host, and from a container it is the container.
 * The two exceptions are deliberate and are the only ones: the published port
 * binds on `${APP_BIND:-127.0.0.1}` (the HOST side of the mapping, where
 * loopback is the safe default), and each healthcheck probes
 * `http://127.0.0.1:<port>` INSIDE its own container, which is where the
 * server it is checking actually listens.
 *
 * Kafka is `kafka:29092`, not `kafka:9092`. The broker advertises two
 * listeners (compose.infra.yml): PLAINTEXT as `kafka:29092` for clients on the
 * network, and PLAINTEXT_HOST as `localhost:9092` for the developer's own
 * fleet. A container that bootstraps against 9092 is answered with metadata
 * naming `localhost:9092` and then dials its own loopback — the one failure
 * that looks like a broker outage and is not. kafka-ui in compose.infra.yml
 * already uses 29092 for the same reason.
 */
import { NEST_KINDS, WEB_KINDS } from './lib.mjs';

export const HEADER = [
  '# GENERATED by scripts/registry/compose.mjs from services.yaml — do not edit',
  '#',
  '#   npm run registry:generate    rewrite this file',
  '#   npm run registry:check       fail if it is stale',
  '#',
  '# Profiles: `admin` is the subset an administrator needs end to end (12);',
  '# `full` is every deployable (35). Compose reads only the ROOT .env.',
  '#',
  '# Included from the root docker-compose.yml with `project_directory: .`, so',
  '# every relative path below — the build context, each env_file — resolves',
  '# from the repository root rather than from infra/docker/. Run it through the',
  '# root file (`docker compose ...`), never with `-f infra/docker/compose.services.yml`',
  '# on its own.',
  '',
].join('\n');

/**
 * The twelve deployables an administrator needs end to end: sign in, the
 * console itself, and the four verticals whose admin consoles do real work.
 * `services.yaml` carries the same twelve as `profiles: [admin]`, and
 * compose.test.mjs asserts the two agree — so a typo in either fails the test
 * rather than quietly shrinking the profile.
 */
export const ADMIN_PROFILE = [
  'api-gateway',
  'auth-service',
  'user-service',
  'admin-service',
  'audit-log-service',
  'notification-service',
  'order-service',
  'payment-service',
  'marketplace-service',
  'grocery-service',
  'taxi-service',
  'web',
];

export function dockerfileFor(s) {
  if (s.kind === 'gateway') return 'infra/docker/api-gateway.Dockerfile';
  if (s.kind === 'core-service') return 'infra/docker/core-service.Dockerfile';
  if (s.kind === 'module-service') return 'infra/docker/module-service.Dockerfile';
  return 'infra/docker/nextjs.Dockerfile';
}

/** The APP build arg: the nest project for apps/api, the module directory for modules. */
export function appArg(s) {
  if (s.kind === 'module-service') return s.path.split('/')[1];
  return s.build.nestProject ?? s.name;
}

/**
 * The variable stem a service is known by to everything else: `order-service`
 * is `ORDER` (`ORDER_SERVICE_HOST`, `ORDER_TCP_PORT`), `audit-log-service` is
 * `AUDIT_LOG`, `marketplace-frontend` is `MARKETPLACE` (`MARKETPLACE_ZONE_ORIGIN`).
 * These are the names the code already reads — `svcHost()` in
 * api-gateway.module.ts and the zone rewrites in apps/web/next.config.mjs.
 */
export const stem = (name) =>
  name
    .replace(/-service$/, '')
    .replace(/-frontend$/, '')
    .replace(/-/g, '_')
    .toUpperCase();

/** The module directory for a module service — `modules/grocery/backend` → `grocery`. */
const moduleDir = (s) => s.path.split('/')[1];

/**
 * What each piece of infrastructure is called on kartseek-network, and the
 * credential that reaches it. Compose interpolates every `${...}` from the ROOT
 * .env, which is the only .env it reads; `npm run env:init` writes it.
 *
 * EVERY nest service gets the whole set, whether or not it declares the
 * dependency. `depends_on` below is what expresses a dependency; this is only
 * an address, and one that is merely unused costs nothing. The alternative was
 * measurably worse: apps/api/.env arrives through `env_file` carrying
 * `KAFKA_BROKERS=localhost:9092`, `DB_HOST=127.0.0.1`, a MONGO_URI and an
 * ELASTICSEARCH_NODE that both name localhost — so a service that did not
 * declare the dependency kept the developer's own machine as the address, and
 * from inside a container that is the container.
 */
const INFRA_ENV = [
  ['DB_HOST', 'postgres'],
  ['DB_PORT', "'5432'"],
  ['DB_NAME', '${POSTGRES_DB:-kartseek_db}'],
  ['REDIS_HOST', 'redis'],
  ['REDIS_PORT', "'6379'"],
  ['REDIS_PASSWORD', '${REDIS_PASSWORD}'],
  ['KAFKA_BROKERS', 'kafka:29092'],
  [
    'MONGO_URI',
    'mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME:-kartseek_catalog}?authSource=admin',
  ],
  // The credential stays in the URL: IN5's elasticsearch-endpoint.ts parses it
  // out into an Authorization header, because fetch() rejects a URL carrying
  // credentials.
  ['ELASTICSEARCH_NODE', 'http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200'],
];

export function profilesOf(s) {
  return ADMIN_PROFILE.includes(s.name) ? '[admin, full]' : '[full]';
}

/**
 * The health route a container probes for itself.
 * Nest deployables serve `health.live`; the console serves no health route, so
 * its cheapest honest signal is the sign-in page, and a zone's is its own base
 * path (`/` on a zone is a 404 — it is mounted under a basePath — which would
 * leave every zone `unhealthy` for ever).
 */
export function healthPathFor(s) {
  if (NEST_KINDS.includes(s.kind)) return s.health.live;
  return s.kind === 'web-zone' ? `${s.basePath}/` : '/admin/login';
}

/** A single-quoted YAML scalar, with the one escape YAML has for the quote itself. */
const q = (v) => `'${String(v).replace(/'/g, "''")}'`;

/**
 * `key: ['a', 'b']` while it fits in prettier's 100 columns, and the bracketed
 * block prettier folds it into when it does not. The generated file is staged
 * like any other, so lint-staged runs prettier over it; emitting anything
 * prettier would rewrite means `registry:check` and the commit hook disagree
 * for ever.
 */
function flowList(indent, key, items) {
  const flow = `${indent}${key}: [${items.map(q).join(', ')}]`;
  if (flow.length <= 100) return flow;
  return [
    `${indent}${key}:`,
    `${indent}  [`,
    ...items.map((i) => `${indent}    ${q(i)},`),
    `${indent}  ]`,
  ].join('\n');
}

/**
 * Where every module's database is, for the same reason INFRA_ENV is emitted
 * whole: apps/api/.env declares all eight `<M>_DB_HOST=127.0.0.1` triples and
 * every one of them would otherwise ride into every container.
 *
 * It is the shared `kartseek_db` in each case — a module owns a schema inside
 * it, not a database. The `kartseek_<module>` names in the root .env belong to
 * the `isolated` profile, where each module gets a Postgres container of its
 * own. No credential here: that is the next group, and it is the one thing a
 * service gets only for its own database.
 */
function moduleDatabaseEnv(reg) {
  const prefixes = [
    ...new Set(
      reg.services
        .map((s) => s.database?.envPrefix)
        .filter((p) => typeof p === 'string' && p !== 'DB'),
    ),
  ];
  return prefixes.flatMap((p) => [
    [`${p}_HOST`, 'postgres'],
    [`${p}_PORT`, "'5432'"],
    [`${p}_NAME`, '${POSTGRES_DB:-kartseek_db}'],
  ]);
}

/**
 * The credential this service connects with.
 *
 * The gateway and the core services are the platform owner. A module service
 * connects AS ITS OWN ROLE — `grocery_user`, created by
 * infra/postgres/init-roles.sh (AUD2-073) — and gets it twice, once under its
 * prefix and once unprefixed. The duplication is the point:
 * `resolveGroceryDbConfig()` and friends read `<M>_DB_*` first and fall back to
 * `DB_*`, and `databaseCredentials()` in @app/database reads `DB_USER` and
 * `DB_NAME` unprefixed no matter what prefix it was given — only the password
 * takes the prefix. With the prefixed set alone, whichever resolver took the
 * unprefixed path would connect as the superuser from apps/api/.env instead.
 *
 * A service with no database of its own still gets the owner credential: it
 * opens no connection, and leaving the variables to apps/api/.env would only
 * put a different copy of the same secret in the container.
 */
function credentialEnv(s) {
  const p = s.database?.envPrefix;
  if (!p || p === 'DB')
    return [
      ['DB_USER', '${POSTGRES_USER:-postgres}'],
      ['DB_PASSWORD', '${POSTGRES_PASSWORD}'],
    ];
  const role = `\${${p}_USER:-${moduleDir(s)}_user}`;
  return [
    [`${p}_USER`, role],
    [`${p}_PASSWORD`, `\${${p}_PASSWORD}`],
    ['DB_USER', role],
    ['DB_PASSWORD', `\${${p}_PASSWORD}`],
  ];
}

/**
 * Every port on the platform, under the variable name main.ts reads it from.
 *
 * Not just this service's own: `ORDER_TCP_PORT` is how order-service learns
 * where to listen AND how the gateway learns where to dial. Emitting the whole
 * map into every container makes the stack self-consistent from the registry
 * alone, instead of depending on a developer's untracked apps/api/.env being
 * in step with it.
 */
function portEnv(reg) {
  const rows = [];
  for (const p of reg.services)
    for (const [kind, name] of Object.entries(p.env ?? {})) rows.push([name, q(p.ports[kind])]);
  return rows;
}

/** Every peer's host, so a TCP client resolves the container and not itself. */
function peerHostEnv(s, reg) {
  return reg.services
    .filter((p) => NEST_KINDS.includes(p.kind) && p.name !== s.name)
    .map((p) => [`${stem(p.name)}_SERVICE_HOST`, p.name]);
}

/**
 * Every gRPC endpoint, under BOTH spellings the codebase uses.
 *
 * `apps/api/.env` declares ten of these and every one of them says
 * `localhost:500x`, so without this the ten ride into all 26 containers.
 * Nothing builds a gRPC client from them today — GrpcClientFactory has no
 * caller and no `Transport.GRPC` client exists — but `health.controller.ts`
 * reports them as the configured endpoint, and a console that says
 * `localhost:5001` from inside a container is saying the container itself.
 *
 * Two spellings because the names in use are not consistent:
 * `AUTH_SERVICE_GRPC_URL` and `ORDER_SERVICE_GRPC_URL` next to
 * `GROCERY_GRPC_URL` and `NOTIFICATION_GRPC_URL`. Deriving both from the
 * registry covers all ten without copying a list of names into this file,
 * which is the drift the registry exists to prevent.
 */
function grpcEndpointEnv(reg) {
  return reg.services
    .filter((p) => NEST_KINDS.includes(p.kind) && p.ports.grpc)
    .flatMap((p) => [
      [`${stem(p.name)}_GRPC_URL`, `${p.name}:${p.ports.grpc}`],
      [`${stem(p.name)}_SERVICE_GRPC_URL`, `${p.name}:${p.ports.grpc}`],
    ]);
}

/**
 * The environment block, as `[comment, entries]` groups. `environment` beats
 * `env_file` in Compose, which is the whole mechanism here: the developer's own
 * .env files supply the ~120 platform variables (JWT_SECRET, MFA, storage, …)
 * and this block overrides every host, port, name and credential in them with
 * container addressing.
 */
export function envGroups(s, reg) {
  if (WEB_KINDS.includes(s.kind)) {
    const groups = [
      ['The image already sets this; nothing here may put it back.', [['NODE_ENV', 'production']]],
      [
        'Server-side fetches go straight to the gateway container. The browser' +
          '\n      # uses the build-time NEXT_PUBLIC_API_URL above, which goes through nginx.',
        [['API_URL', 'http://api-gateway:3001/api/v1']],
      ],
    ];
    if (s.kind === 'web-shell') {
      const zones = reg.services.filter((z) => z.kind === 'web-zone');
      if (zones.length)
        groups.push([
          'Where the shell rewrites each vertical path (next.config.mjs).',
          zones.map((z) => [`${stem(z.name)}_ZONE_ORIGIN`, `http://${z.name}:${z.ports.http}`]),
        ]);
    }
    return groups;
  }

  const groups = [
    [
      'The image sets this too, but apps/api/.env says development and env_file' +
        '\n      # wins over the image. Production here also switches DEV_AUTH_BYPASS off' +
        '\n      # (it is gated on NODE_ENV) and makes the gateway bind 0.0.0.0.',
      [['NODE_ENV', 'production']],
    ],
  ];

  groups.push([
    'Infrastructure, by its compose service name — the whole set, whether or not' +
      '\n      # this service declares the dependency: depends_on below is what expresses' +
      '\n      # one, and apps/api/.env would otherwise leave the unclaimed ones pointing' +
      '\n      # at the developer’s own machine.',
    INFRA_ENV,
  ]);
  groups.push([
    'Every module database: one schema each, inside the shared one.',
    moduleDatabaseEnv(reg),
  ]);
  groups.push([
    'How this service signs in, and no SSL — the images run NODE_ENV=production,' +
      '\n      # which turns SSL on by default, and this Postgres speaks plaintext on a' +
      '\n      # private network.',
    [...credentialEnv(s), ['DB_SSL', "'false'"]],
  ]);

  if (s.kafka) groups.push(['Kafka consumer group.', [['KAFKA_GROUP_ID', s.kafka.groupId]]]);

  groups.push(['Every port on the platform, from the registry.', portEnv(reg)]);
  groups.push(["Every peer's container, so a TCP client never dials itself.", peerHostEnv(s, reg)]);
  groups.push(['Every gRPC endpoint, under both spellings the code uses.', grpcEndpointEnv(reg)]);
  return groups;
}

/**
 * Which .env files a container reads, and whether it must find them.
 *
 * The root .env is required — it holds POSTGRES_*, REDIS_PASSWORD,
 * ELASTIC_PASSWORD, MONGO_* and the eight module role credentials, and the
 * stack cannot work without it. The workspace files are optional and untracked:
 * they are where the ~120 platform variables live (JWT_SECRET, ENCRYPTION_KEY,
 * the MFA and storage settings, the DDoS limits). A container built without
 * them boots into a Joi validation failure naming the first missing one.
 *
 * A web deployable gets the root .env alone: apps/web/.env.local is a developer's
 * localhost wiring, and NEXT_PUBLIC_* are inlined at build time anyway.
 */
export function envFilesFor(s) {
  // A Next server reads none of it — NEXT_PUBLIC_* are inlined at build time
  // and everything else it needs is in `environment` below — while the root
  // .env holds every datastore credential on the platform. Keeping it out of
  // the console image means the console image cannot leak one.
  if (WEB_KINDS.includes(s.kind)) return [];
  const files = [
    ['.env', true],
    ['apps/api/.env', false],
  ];
  if (s.kind === 'module-service') files.push([`${s.path}/.env`, false]);
  return files;
}

function buildBlock(s) {
  const out = ['    build:', '      context: .', `      dockerfile: ${dockerfileFor(s)}`];
  if (s.kind === 'gateway') {
    // api-gateway.Dockerfile declares no ARG at all: its port, its health route
    // and its entry point are fixed to the one service it builds. Passing args
    // it never consumes only earns a BuildKit warning per build.
    out.push('      # api-gateway.Dockerfile takes no build args — the gateway is the only');
    out.push('      # thing it builds, so its port and health route are baked in.');
    return out.join('\n');
  }
  out.push('      args:');
  if (WEB_KINDS.includes(s.kind)) {
    out.push(
      `        WORKSPACE_DIR: ${s.path}`,
      `        PORT: ${q(s.ports.http)}`,
      `        HEALTH_PATH: ${healthPathFor(s)}`,
      // NEXT_PUBLIC_* are inlined into the client bundle at build time, so they
      // are build args and changing one means rebuilding. All three are
      // required: each omission fails the build naming a route, not a variable.
      '        NEXT_PUBLIC_API_URL: ${COMPOSE_API_URL:-http://nginx/api/v1}',
      '        NEXT_PUBLIC_WS_URL: ${COMPOSE_WS_URL:-ws://nginx}',
      '        API_URL: http://api-gateway:3001/api/v1',
    );
  } else {
    out.push(
      `        APP: ${appArg(s)}`,
      `        PORT: ${q(s.ports.http)}`,
      `        HEALTH_PATH: ${healthPathFor(s)}`,
    );
  }
  return out.join('\n');
}

function envFileBlock(s) {
  const files = envFilesFor(s);
  if (!files.length) return null;
  return [
    '    env_file:',
    ...files.flatMap(([path, required]) => [
      `      - path: ${path}`,
      `        required: ${required}`,
    ]),
  ].join('\n');
}

function environmentBlock(s, reg) {
  const lines = ['    environment:'];
  for (const [comment, entries] of envGroups(s, reg)) {
    if (!entries.length) continue;
    lines.push(`      # ${comment}`);
    for (const [k, v] of entries) lines.push(`      ${k}: ${v}`);
  }
  return lines.join('\n');
}

function dependsOnBlock(s) {
  const deps = s.dependsOn ?? [];
  if (!deps.length) return null;
  return [
    '    depends_on:',
    ...deps.flatMap((d) => [`      ${d}:`, '        condition: service_healthy']),
  ].join('\n');
}

function healthcheckBlock(s) {
  const path = healthPathFor(s);
  const lines = ['    healthcheck:'];
  if (!path) {
    // No service has a null health route today; this keeps the generator honest
    // if one ever does, because an image with no check can never satisfy
    // `condition: service_healthy` and would hang every dependent service.
    lines.push('      # No HTTP health route in the registry — the port opening is all there is.');
    lines.push(
      flowList('      ', 'test', ['CMD-SHELL', `nc -z 127.0.0.1 ${s.ports.http} || exit 1`]),
    );
  } else {
    lines.push(
      flowList('      ', 'test', [
        'CMD-SHELL',
        `wget -qO- http://127.0.0.1:${s.ports.http}${path} >/dev/null || exit 1`,
      ]),
    );
  }
  lines.push(
    '      interval: 15s',
    '      timeout: 5s',
    '      retries: 10',
    // A Next server compiles its first route on demand, so it needs longer than
    // an API image before a failed check starts counting against it.
    `      start_period: ${WEB_KINDS.includes(s.kind) ? '60s' : '40s'}`,
  );
  return lines.join('\n');
}

export function renderService(s, reg) {
  const parts = [
    `  ${s.name}:`,
    buildBlock(s),
    `    image: ${s.image}:\${KARTSEEK_TAG:-dev}`,
    `    container_name: kartseek-${s.name}`,
    '    restart: unless-stopped',
    `    profiles: ${profilesOf(s)}`,
    envFileBlock(s),
    environmentBlock(s, reg),
    '    ports:',
    ...Object.values(s.ports).map((p) => `      - ${q(`\${APP_BIND:-127.0.0.1}:${p}:${p}`)}`),
    dependsOnBlock(s),
    healthcheckBlock(s),
  ];
  return parts.filter((p) => p !== null).join('\n');
}

export function renderComposeServices(reg) {
  const body = reg.services.map((s) => renderService(s, reg)).join('\n\n');
  return [
    HEADER,
    'services:',
    body,
    '',
    'networks:',
    '  default:',
    // Not `external: true`. compose.infra.yml declares the same network without
    // it, and Compose merges the two top-level blocks — so `external` would
    // apply to `npm run infra:up` as well, and on a machine that has never run
    // the stack there is nothing to attach to. Compose creates it on the first
    // `up` from either file and both then share it.
    '    name: kartseek-network',
    '',
  ].join('\n');
}
