import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  renderReadmeBlock,
  replaceBlock,
  renderServicesTable,
  renderPlatformBlock,
  generateAll,
  PLATFORM_TARGETS,
} from './generate.mjs';

const order = {
  name: 'order-service',
  kind: 'core-service',
  path: 'apps/api/apps/order-service',
  image: 'kartseek/order-service',
  build: { workspace: 'kartseek-api', nestProject: 'order-service' },
  ports: { http: 3014, tcp: 4004, grpc: 5002 },
  env: { http: 'ORDER_SERVICE_PORT', tcp: 'ORDER_TCP_PORT', grpc: 'ORDER_GRPC_PORT' },
  health: { live: '/health', ready: '/health/ready' },
  database: { name: 'kartseek_db', schema: 'order', envPrefix: 'DB' },
  dependsOn: ['postgres', 'redis'],
};
const zone = {
  name: 'grocery-frontend',
  kind: 'web-zone',
  path: 'modules/grocery/frontend',
  image: 'kartseek/grocery-frontend',
  build: { workspace: '@kartseek/grocery-frontend' },
  ports: { http: 3003 },
  basePath: '/grocery',
};

test('renderReadmeBlock lists every port with its variable, then database and dependencies', () => {
  const block = renderReadmeBlock(order);
  assert.match(block, /\| HTTP \| 3014 \| `ORDER_SERVICE_PORT` \|/);
  assert.match(block, /\| TCP \(message patterns\) \| 4004 \| `ORDER_TCP_PORT` \|/);
  assert.match(block, /\| gRPC \| 5002 \| `ORDER_GRPC_PORT` \|/);
  assert.match(block, /Database: `kartseek_db`, schema `order` \(`DB_\*`\)/);
  assert.match(block, /Depends on: postgres, redis/);
  assert.match(block, /Health: `\/health` \(live\), `\/health\/ready` \(ready\)/);
  assert.match(block, /<!-- prettier-ignore-start -->/);
  assert.match(block, /<!-- prettier-ignore-end -->/);
  assert.equal((block.match(/prettier-ignore-start/g) || []).length, 1);
  assert.equal((block.match(/prettier-ignore-end/g) || []).length, 1);
  // Prettier needs a blank line between the block's last paragraph and the end marker
  assert.ok(block.endsWith('\n'), 'block must end with a newline for prettier compliance');
});

test('renderReadmeBlock for a zone gives port, base path and image', () => {
  const block = renderReadmeBlock(zone);
  assert.match(block, /\| HTTP \| 3003 \|/);
  assert.match(block, /Mounted by the shell at `\/grocery`/);
  assert.match(block, /Image: `kartseek\/grocery-frontend`/);
});

test('replaceBlock swaps the content between markers and keeps everything else', () => {
  const md = '# T\n\n<!-- registry:start -->\nold\n<!-- registry:end -->\n\ntail\n';
  assert.equal(
    replaceBlock(md, 'new'),
    '# T\n\n<!-- registry:start -->\nnew\n<!-- registry:end -->\n\ntail\n',
  );
  assert.equal(replaceBlock('# no markers\n', 'new'), null);
});

test('renderServicesTable has one row per entry and a generated header', () => {
  const table = renderServicesTable({ services: [order, zone] });
  assert.match(
    table,
    /^<!-- GENERATED by scripts\/registry\/generate\.mjs from services\.yaml — do not edit -->/,
  );
  assert.equal((table.match(/^\| `/gm) || []).length, 2);
  assert.equal((table.match(/prettier-ignore-start/g) || []).length, 1);
  assert.equal((table.match(/prettier-ignore-end/g) || []).length, 1);
});

test('renderPlatformBlock leads with the generated notice and renders one row per entry', () => {
  const block = renderPlatformBlock({ services: [order, zone] });
  assert.match(block, /_Generated from `services.yaml` by `npm run registry:generate`/);
  assert.equal((block.match(/^\| `/gm) || []).length, 2);
  assert.match(block, /\| `order-service` \| core service \|/);
  assert.match(block, /\| `grocery-frontend` \| web zone \|/);
  assert.equal((block.match(/prettier-ignore-start/g) || []).length, 1);
  assert.equal((block.match(/prettier-ignore-end/g) || []).length, 1);
});

test('generateAll writes the compose file as a whole-file target', () => {
  // A temporary root with none of the marker documents in it: every other
  // target is skipped for want of a README, which leaves exactly the two
  // whole-file targets to prove.
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'registry-generate-'));
  try {
    const result = generateAll({ services: [order, zone] }, root);
    assert.ok(result.written.includes('infra/docker/compose.services.yml'));
    const written = fs.readFileSync(path.join(root, 'infra/docker/compose.services.yml'), 'utf8');
    assert.match(written, /^# GENERATED by scripts\/registry\/compose\.mjs/);
    assert.match(written, /container_name: kartseek-order-service/);
    // And it is then seen as fresh, which is what registry:check relies on.
    assert.deepEqual(generateAll({ services: [order, zone] }, root, { check: true }).stale, []);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('PLATFORM_TARGETS names the four platform-wide documents', () => {
  assert.deepEqual(PLATFORM_TARGETS, [
    'README.md',
    'docs/guides/running-services.md',
    'apps/api/README.md',
    'apps/api/docs/runbook.md',
  ]);
});
