#!/usr/bin/env node
/**
 * Renders everything derived from services.yaml.
 *
 *   node scripts/registry/generate.mjs           write (npm run registry:generate)
 *   node scripts/registry/generate.mjs --check   exit 1 if anything is stale
 *
 * Outputs: docs/architecture/services.md (whole file), the platform table
 * between markers in README.md, docs/guides/running-services.md,
 * apps/api/README.md and apps/api/docs/runbook.md, and the block between
 * markers in every entry's README.md. A README without markers is skipped
 * and listed, not created. Tables are wrapped in prettier range-ignore
 * comments so format:check and registry:check agree.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRegistry, repoRoot, NEST_KINDS } from './lib.mjs';

export const START = '<!-- registry:start -->';
export const END = '<!-- registry:end -->';
const PRETTIER_OFF = '<!-- prettier-ignore-start -->';
const PRETTIER_ON = '<!-- prettier-ignore-end -->';
const HEADER = '<!-- GENERATED by scripts/registry/generate.mjs from services.yaml — do not edit -->';
const KIND_LABEL = { gateway: 'API gateway', 'core-service': 'core service', 'module-service': 'module service', 'web-shell': 'web shell', 'web-zone': 'web zone' };

/**
 * Documents that describe the whole platform and carry the full table
 * between their markers, rather than one entry's block. Root README, the
 * running-services guide, the API workspace README and its runbook.
 */
export const PLATFORM_TARGETS = [
  'README.md',
  'docs/guides/running-services.md',
  'apps/api/README.md',
  'apps/api/docs/runbook.md',
];

const code = (v) => (v == null ? '—' : `\`${v}\``);

export function renderReadmeBlock(s) {
  const lines = [
    '',
    '_Generated from `services.yaml` by `npm run registry:generate`; edit the registry, not this block._',
    '',
    PRETTIER_OFF,
    '| Purpose | Port | Environment variable |',
    '| --- | --- | --- |',
    `| HTTP | ${s.ports.http} | ${s.env?.http ? code(s.env.http) : '—'} |`,
  ];
  if (s.ports.tcp) lines.push(`| TCP (message patterns) | ${s.ports.tcp} | ${code(s.env.tcp)} |`);
  if (s.ports.grpc) lines.push(`| gRPC | ${s.ports.grpc} | ${code(s.env.grpc)} |`);
  lines.push(PRETTIER_ON);
  lines.push('');
  if (NEST_KINDS.includes(s.kind)) {
    lines.push(`Health: ${s.health.live ? `${code(s.health.live)} (live)` : 'no HTTP health route yet'}${s.health.ready ? `, ${code(s.health.ready)} (ready)` : ''}.`);
    lines.push(s.database ? `Database: ${code(s.database.name)}, schema ${code(s.database.schema)} (${code(`${s.database.envPrefix}_*`)}).` : 'Database: none (owns no tables).');
    lines.push(`Image: ${code(s.image)}. Depends on: ${s.dependsOn.join(', ') || 'nothing'}.${s.kafka ? ` Kafka group: ${code(s.kafka.groupId)}.` : ''}`);
  } else {
    lines.push(s.kind === 'web-zone' ? `Mounted by the shell at ${code(s.basePath)}; open it through http://localhost:3000${s.basePath}.` : 'The shell: serves the top-level routes and rewrites each vertical path to its zone.');
    lines.push(`Image: ${code(s.image)}. Workspace: ${code(s.build.workspace)}.`);
  }
  lines.push(''); // Prettier needs a blank line between the block's last paragraph and the end marker
  return lines.join('\n');
}

export function replaceBlock(markdown, block) {
  const a = markdown.indexOf(START), b = markdown.indexOf(END);
  if (a === -1 || b === -1 || b < a) return null;
  return markdown.slice(0, a + START.length) + '\n' + block + '\n' + markdown.slice(b);
}

const TABLE_HEAD = [
  '| Name | Kind | Path | HTTP | TCP | gRPC | Database / schema | Health or base path | Depends on |',
  '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
];

function renderRows(reg) {
  return reg.services.map((s) => {
    const db = NEST_KINDS.includes(s.kind) ? (s.database ? `${s.database.name} / ${s.database.schema}` : '—') : '—';
    const health = NEST_KINDS.includes(s.kind) ? (s.health.live ?? '—') : s.basePath ?? '/';
    return `| ${code(s.name)} | ${KIND_LABEL[s.kind]} | ${code(s.path)} | ${s.ports.http} | ${s.ports.tcp ?? '—'} | ${s.ports.grpc ?? '—'} | ${db} | ${code(health)} | ${(s.dependsOn ?? []).join(', ') || '—'} |`;
  });
}

export function renderPlatformBlock(reg) {
  return [
    '',
    '_Generated from `services.yaml` by `npm run registry:generate`; edit the registry, not this block._',
    '',
    PRETTIER_OFF,
    ...TABLE_HEAD,
    ...renderRows(reg),
    PRETTIER_ON,
  ].join('\n');
}

export function renderServicesTable(reg) {
  return [
    HEADER,
    '',
    '# Services',
    '',
    `${reg.services.length} deployables, declared in [\`services.yaml\`](../../services.yaml). Ports are the local defaults; each is read from the environment variable named in the deployable's README.`,
    '',
    PRETTIER_OFF,
    ...TABLE_HEAD,
    ...renderRows(reg),
    PRETTIER_ON,
    '',
  ].join('\n');
}

function writeAtomic(file, content) {
  const tmp = `${file}.tmp`;
  fs.writeFileSync(tmp, content);
  fs.renameSync(tmp, file);
}

export function generateAll(reg, root, { check = false } = {}) {
  const result = { written: [], skipped: [], stale: [] };
  const targets = [
    { rel: 'docs/architecture/services.md', next: () => renderServicesTable(reg), whole: true },
    ...PLATFORM_TARGETS.map((rel) => ({ rel, next: (cur) => replaceBlock(cur, renderPlatformBlock(reg)), whole: false })),
    ...reg.services.map((s) => ({ rel: `${s.path}/README.md`, next: (cur) => replaceBlock(cur, renderReadmeBlock(s)), whole: false })),
  ];
  for (const t of targets) {
    const file = path.join(root, t.rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (!t.whole && current === null) { result.skipped.push(`${t.rel} (no README yet)`); continue; }
    const next = t.whole ? t.next() : t.next(current);
    if (next === null) { result.skipped.push(`${t.rel} (no ${START} markers)`); continue; }
    if (next === current) continue;
    if (check) result.stale.push(`${t.rel} is stale — run npm run registry:generate`);
    else { fs.mkdirSync(path.dirname(file), { recursive: true }); writeAtomic(file, next); result.written.push(t.rel); }
  }
  return result;
}

export const checkGenerated = (reg, root) => generateAll(reg, root, { check: true }).stale;

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const root = repoRoot();
  const r = generateAll(loadRegistry(root), root, { check });
  for (const w of r.written) console.log(`wrote   ${w}`);
  for (const s of r.skipped) console.log(`skipped ${s}`);
  for (const s of r.stale) console.error(`✗ ${s}`);
  if (!check) console.log(`${r.written.length} file(s) written, ${r.skipped.length} skipped`);
  process.exit(r.stale.length ? 1 : 0);
}
