import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderReadmeBlock, replaceBlock, renderServicesTable, renderPlatformBlock, PLATFORM_TARGETS } from './generate.mjs';

const order = {
  name: 'order-service', kind: 'core-service', path: 'apps/api/apps/order-service', image: 'kartseek/order-service',
  build: { workspace: 'kartseek-api', nestProject: 'order-service' },
  ports: { http: 3014, tcp: 4004, grpc: 5002 }, env: { http: 'ORDER_SERVICE_PORT', tcp: 'ORDER_TCP_PORT', grpc: 'ORDER_GRPC_PORT' },
  health: { live: '/health', ready: '/health/ready' }, database: { name: 'kartseek_db', schema: 'order', envPrefix: 'DB' },
  dependsOn: ['postgres', 'redis'],
};
const zone = { name: 'grocery-frontend', kind: 'web-zone', path: 'modules/grocery/frontend', image: 'kartseek/grocery-frontend',
  build: { workspace: '@kartseek/grocery-frontend' }, ports: { http: 3003 }, basePath: '/grocery' };

test('renderReadmeBlock lists every port with its variable, then database and dependencies', () => {
  const block = renderReadmeBlock(order);
  assert.match(block, /\| HTTP \| 3014 \| `ORDER_SERVICE_PORT` \|/);
  assert.match(block, /\| TCP \(message patterns\) \| 4004 \| `ORDER_TCP_PORT` \|/);
  assert.match(block, /\| gRPC \| 5002 \| `ORDER_GRPC_PORT` \|/);
  assert.match(block, /Database: `kartseek_db`, schema `order` \(`DB_\*`\)/);
  assert.match(block, /Depends on: postgres, redis/);
  assert.match(block, /Health: `\/health` \(live\), `\/health\/ready` \(ready\)/);
});

test('renderReadmeBlock for a zone gives port, base path and image', () => {
  const block = renderReadmeBlock(zone);
  assert.match(block, /\| HTTP \| 3003 \|/);
  assert.match(block, /Mounted by the shell at `\/grocery`/);
  assert.match(block, /Image: `kartseek\/grocery-frontend`/);
});

test('replaceBlock swaps the content between markers and keeps everything else', () => {
  const md = '# T\n\n<!-- registry:start -->\nold\n<!-- registry:end -->\n\ntail\n';
  assert.equal(replaceBlock(md, 'new'), '# T\n\n<!-- registry:start -->\nnew\n<!-- registry:end -->\n\ntail\n');
  assert.equal(replaceBlock('# no markers\n', 'new'), null);
});

test('renderServicesTable has one row per entry and a generated header', () => {
  const table = renderServicesTable({ services: [order, zone] });
  assert.match(table, /^<!-- GENERATED by scripts\/registry\/generate\.mjs from services\.yaml — do not edit -->/);
  assert.equal((table.match(/^\| `/gm) || []).length, 2);
});

test('renderPlatformBlock leads with the generated notice and renders one row per entry', () => {
  const block = renderPlatformBlock({ services: [order, zone] });
  assert.match(block, /^_Generated from `services.yaml` by `npm run registry:generate`/);
  assert.equal((block.match(/^\| `/gm) || []).length, 2);
  assert.match(block, /\| `order-service` \| core service \|/);
  assert.match(block, /\| `grocery-frontend` \| web zone \|/);
});

test('PLATFORM_TARGETS names the four platform-wide documents', () => {
  assert.deepEqual(PLATFORM_TARGETS, [
    'README.md',
    'docs/guides/running-services.md',
    'apps/api/README.md',
    'apps/api/docs/runbook.md',
  ]);
});
