/**
 * Renders infra/k8s/microservices-generated.yaml from services.yaml.
 *
 * The file it replaces was produced by infra/k8s/gen-microservices.sh from a
 * hand-written table of 22 services and ports, and it had drifted in the two
 * ways a second copy of the truth always drifts:
 *
 *   • 42 of its 44 probes were `tcpSocket` (AUD2-002). A TCP probe passes the
 *     moment Nest binds the port, so a pod whose database is unreachable stayed
 *     in its Service's endpoint list and took production traffic. IN1 gave every
 *     deployable `/health` and `/health/ready` — readiness answers 503 when a
 *     dependency is down — so the probes now come from the registry's
 *     `health.live` / `health.ready` on `ports.http`.
 *   • the table itself was a second port map. `services.yaml` is the first one,
 *     `npm run registry:check` fails when this file falls behind it, and the
 *     pre-commit hook runs that check.
 *
 * WHAT IS IN HERE, AND WHAT IS NOT
 *
 * Every registry entry except the gateway: 25 Nest services and the 9 Next
 * deployables, one Deployment and one Service each. The gateway keeps its
 * hand-written `api-gateway.yaml` because it carries an HPA, a
 * PodDisruptionBudget, a metrics port and node affinity that no other workload
 * has — but its probe paths come from the same registry entry, and
 * k8s.test.mjs asserts them.
 *
 * `microservices.yaml` held hand-written copies of auth/order/payment. They are
 * generated here now: two definitions of one Deployment in one directory is a
 * `kubectl apply -f infra/k8s/` where the last file read wins, which is the
 * same drift in a louder place.
 *
 * ADDRESSING
 *
 * Datastores answer to their Kubernetes Service name — `postgres`, `redis`,
 * `kafka`, `mongodb`, `elasticsearch`, each `<name>.kartseek.svc.cluster.local`.
 * Nothing here may say localhost: in a pod that is the pod. The one exception
 * is a container's own bind address (`<STEM>_HTTP_HOST: 0.0.0.0`), which is
 * about where a listener accepts, not where a client dials.
 *
 * Kafka is the plain `kafka:9092` listener, NOT compose's `kafka:29092`. That
 * split is a Compose artefact: the broker there advertises PLAINTEXT_HOST as
 * `localhost:9092` for the developer's own fleet, so a container bootstrapping
 * against 9092 is answered with its own loopback. `databases.yaml` advertises
 * PLAINTEXT_HOST as the POD's FQDN instead, so 9092 is right in the cluster.
 * The `wait-for-kafka` init container below dials `kafka…:9092` through the
 * headless Service; the ConfigMap's `KAFKA_BROKERS` names the pod directly
 * (`kafka-0.kafka…:9092`), which is the address the broker advertises back and
 * therefore the one a client must bootstrap from.
 *
 * SECRETS
 *
 * No password literal is rendered. Everything a service signs in with arrives
 * through `envFrom: secretRef: kartseek-secrets`, or — where one service needs
 * one specific key under a different name — through a `secretKeyRef`. A
 * credential that has to appear inside a URL (`MONGO_URI`,
 * `ELASTICSEARCH_NODE`) is assembled by the kubelet from `$(VAR)` references
 * to keys the Secret already supplied, so the manifest carries the shape and
 * never the value.
 *
 * IMAGE TAG
 *
 * `<image>:${KARTSEEK_TAG}`, substituted at deploy time by `deploy.sh` (which
 * defaults it to `dev`). The tag was `2.0.0` here and `2.1.0` for
 * marketplace-service; no image with either tag has ever been built, so every
 * pod would have been `ErrImagePull`. A literal `${KARTSEEK_TAG}` that reaches
 * the cluster unsubstituted fails as `InvalidImageName` on the first pod, which
 * is a failure you can see.
 */
import { NEST_KINDS, WEB_KINDS } from './lib.mjs';
// The same two helpers the compose renderer uses, imported rather than copied:
// a health path that disagreed between the two stacks is exactly the drift
// this generator exists to stop.
import { healthPathFor, stem } from './compose.mjs';

export const NAMESPACE = 'kartseek';
const SVC = (name) => `${name}.${NAMESPACE}.svc.cluster.local`;

export const HEADER = [
  '# GENERATED by scripts/registry/k8s.mjs from services.yaml — do not edit',
  '#',
  '#   npm run registry:generate    rewrite this file',
  '#   npm run registry:check       fail if it is stale (runs pre-commit)',
  '#',
  '# One Deployment and one Service for every registry entry except the gateway,',
  '# which is hand-written in api-gateway.yaml. Probes come from the registry:',
  '# livenessProbe and startupProbe on `health.live`, readinessProbe on',
  '# `health.ready` — the route that answers 503 when a dependency is down, and',
  '# 200 while it is merely degraded, so a warm-cache problem does not empty the',
  '# Service (IN1).',
  '#',
  '# Images are `<image>:${KARTSEEK_TAG}`; deploy.sh substitutes the tag and',
  '# defaults it to `dev`. Applying this file with plain `kubectl apply` leaves',
  '# the literal in place and the pod reports InvalidImageName.',
  '#',
  '# NOT EVERY IMAGE HERE CAN BE BUILT YET. No kartseek/* image is published',
  '# anywhere, and of the nine Next deployables only `web` has an image at all:',
  "# the eight zones need `output: 'standalone'` in their next.config.mjs, which",
  '# is Task IN11. Their Deployments are declared here so the wiring is reviewed',
  '# and ready; `deploy.sh` skips any Deployment whose image the local Docker',
  '# daemon does not have, naming it, rather than leaving pods in ErrImagePull.',
  '',
].join('\n');

/**
 * Which datastore each `dependsOn` entry is, in the cluster.
 *
 * `wait-for-<x>` init containers are generated from this, so a service waits
 * for exactly what its registry entry claims to need — the old generator gave
 * every one of the 22 a `wait-for-db`, including the nine that open no Postgres
 * connection at all.
 */
export const INFRA_ENDPOINT = {
  postgres: { host: SVC('postgres'), port: 5432 },
  redis: { host: SVC('redis'), port: 6379 },
  kafka: { host: SVC('kafka'), port: 9092 },
  mongodb: { host: SVC('mongodb'), port: 27017 },
  elasticsearch: { host: SVC('elasticsearch'), port: 9200 },
};

/**
 * Services whose HTTP listener is bound to loopback inside the container, where
 * the kubelet cannot reach it.
 *
 * `modules/pharmacy/backend/src/main.ts` calls `app.listen(port, '127.0.0.1')`
 * with no environment override — deliberate, because that surface is
 * unguarded — so an httpGet probe against it fails for ever. Its TCP transport
 * binds 0.0.0.0 and is what the gateway actually consumes, so that is what is
 * probed. This is a weaker check than the other 24 get, and the fix is in the
 * service: give it the `MARKETPLACE_HTTP_HOST` treatment (bind wide, and let
 * HttpSurfaceGuard keep /health the only route) and delete the name from here.
 */
export const LOOPBACK_HTTP = new Set(['pharmacy-service']);

/**
 * The uid each image actually runs as. `runAsUser` that disagrees with the
 * image is one of the things `--validate=strict` cannot see (2026-08-13 audit):
 * every manifest here said 1000, and only the core-service images are 1000.
 *
 *   infra/docker/core-service.Dockerfile    USER node    → uid 1000
 *   infra/docker/api-gateway.Dockerfile     USER nestjs  → uid 1001
 *   infra/docker/module-service.Dockerfile  USER nestjs  → uid 1001
 *   infra/docker/nextjs.Dockerfile          USER nextjs  → uid 1001
 */
export function runAsUserFor(s) {
  return s.kind === 'core-service' ? 1000 : 1001;
}

/**
 * Per-service departures from the defaults, and the only place they belong: the
 * generated file used to carry hand-written marketplace changes that the old
 * generator silently reverted on its next run.
 *
 * SIZE ONLY. This map held a `postgresHost` for marketplace-service, pointing
 * its init container and its DB_HOST at a dedicated `postgres-marketplace`
 * instance while Compose put the same service on the shared `postgres` as a
 * tenant role — one module running against two different databases depending on
 * which stack you started, with no gate that could notice, because
 * `registry:check` and `k8s.test.mjs` both import the module that defined the
 * exception. The coordinator's ruling is the shared instance everywhere; the
 * dedicated StatefulSet stays in databases.yaml as the documented `isolated`
 * option, referenced by no Deployment.
 *
 * Nothing that decides WHERE a service connects may live here again. A host that
 * has to differ is a field in `services.yaml`, validated by `lib.mjs`, so the
 * drift gates can see it.
 */
export const OVERRIDES = {
  'marketplace-service': {
    // The highest-volume path in the platform.
    resources: { cpu: '300m', memory: '384Mi', cpuLimit: '1000m', memoryLimit: '1Gi' },
  },
};

const DEFAULT_RESOURCES = {
  cpu: '200m',
  memory: '256Mi',
  cpuLimit: '500m',
  memoryLimit: '512Mi',
};
// A Next server holds a compiled route cache and renders on the server; 512Mi
// is where the console starts to OOM under a page that fans out to the gateway.
const WEB_RESOURCES = {
  cpu: '100m',
  memory: '256Mi',
  cpuLimit: '500m',
  memoryLimit: '1Gi',
};

export const resourcesFor = (s) =>
  OVERRIDES[s.name]?.resources ?? (WEB_KINDS.includes(s.kind) ? WEB_RESOURCES : DEFAULT_RESOURCES);

/**
 * The two paths a pod is probed on.
 *
 * Nest deployables serve both from `@app/common`'s HealthModule. A Next
 * deployable serves no health route, so its cheapest honest signal is a page it
 * must be able to render — the same one the Docker HEALTHCHECK uses, through
 * compose.mjs's `healthPathFor`, so the two stacks cannot disagree: the sign-in
 * page for the shell, and a zone's own base path (`/` on a zone is a 404).
 */
export function probePaths(s) {
  if (NEST_KINDS.includes(s.kind))
    return { live: s.health.live, ready: s.health.ready ?? s.health.live };
  const p = healthPathFor(s);
  return { live: p, ready: p };
}

/** A single-quoted YAML scalar, with the one escape YAML has for the quote itself. */
const q = (v) => `'${String(v).replace(/'/g, "''")}'`;

const indent = (n, lines) => lines.map((l) => (l === '' ? l : ' '.repeat(n) + l));

/**
 * The ports a Service publishes.
 *
 * pharmacy-service's HTTP listener is on loopback, so a Service port aimed at
 * it is a black hole that resolves, connects and answers nothing — publish only
 * the transports that are actually bound wide.
 */
export function servicePorts(s) {
  const entries = Object.entries(s.ports).filter(
    ([kind]) => !(kind === 'http' && LOOPBACK_HTTP.has(s.name)),
  );
  return entries.flatMap(([kind, port]) => [
    `- name: ${kind}`,
    `  protocol: TCP`,
    `  port: ${port}`,
    `  targetPort: ${port}`,
  ]);
}

function initContainers(s) {
  const deps = s.dependsOn ?? [];
  if (!deps.length) return [];
  const lines = [
    'initContainers:',
    // Not tidiness: the namespace ResourceQuota tracks requests/limits and its
    // admission check walks init containers too, so a resourceless one makes
    // the whole pod un-creatable (2026-08-13 audit).
    '  # `resources` is mandatory — the ResourceQuota admission check walks init',
    '  # containers and rejects the pod when they are unset.',
  ];
  for (const d of deps) {
    const { host, port } = INFRA_ENDPOINT[d];
    lines.push(
      `  - name: wait-for-${d}`,
      '    image: busybox:1.36',
      '    command:',
      '      - sh',
      '      - -c',
      `      - ${q(`until nc -z ${host} ${port}; do echo waiting for ${d}; sleep 2; done`)}`,
      '    resources:',
      '      requests:',
      `        cpu: ${q('10m')}`,
      `        memory: ${q('16Mi')}`,
      '      limits:',
      `        cpu: ${q('50m')}`,
      `        memory: ${q('64Mi')}`,
    );
  }
  return lines;
}

/**
 * How this service signs in to Postgres.
 *
 * The ConfigMap gives every pod `DB_USER: postgres` and the Secret gives it
 * `DB_PASSWORD`, which is the platform owner. A module service connects as its
 * OWN role — `grocery_user`, created by infra/postgres/init-roles.sh, which
 * databases.yaml mounts into the Postgres StatefulSet — and needs it twice:
 * `resolveGroceryDbConfig()` reads `GROCERY_DB_*` first, while
 * `databaseCredentials()` in @app/database reads `DB_USER` and `DB_NAME`
 * unprefixed whatever prefix it was handed. With the prefixed pair alone,
 * whichever resolver took the unprefixed path would connect as the superuser.
 *
 * A service whose registry entry says `database: null` gets `unused` — it opens
 * no connection, and inheriting the superuser credential from the ConfigMap
 * would put it in nine more pods for nothing. Blank rather than `unused` is not
 * an option: @app/common's Joi schema rejects an empty DB_USER and the pod
 * crash-loops on `"DB_USER" is not allowed to be empty` (IN7 found that in
 * Compose).
 */
export function credentialEnv(s) {
  if (!NEST_KINDS.includes(s.kind)) return [];
  const p = s.database?.envPrefix;
  if (!p)
    return [
      { name: 'DB_NAME', value: 'unused' },
      { name: 'DB_USER', value: 'unused' },
      { name: 'DB_PASSWORD', value: '' },
    ];
  // `DB`: the shared database, as its owner. Host, port, name and user come
  // from the ConfigMap; only the password has to be named, because the Secret
  // calls it POSTGRES_PASSWORD — the name .env.example, Compose and the
  // Postgres StatefulSet all use — and this service reads DB_PASSWORD.
  if (p === 'DB')
    return [{ name: 'DB_PASSWORD', valueFrom: { secretKeyRef: 'POSTGRES_PASSWORD' } }];
  const module = s.path.split('/')[1];
  return [
    // Host and port too, not only the credential: marketplace-service is on an
    // instance of its own, so leaving the unprefixed DB_HOST at the shared
    // `postgres` would send whichever resolver took the unprefixed path to a
    // different database — with a role that exists in both.
    { name: 'DB_HOST', valueFrom: { configMapKeyRef: `${p}_HOST` } },
    { name: 'DB_PORT', valueFrom: { configMapKeyRef: `${p}_PORT` } },
    { name: 'DB_NAME', valueFrom: { configMapKeyRef: `${p}_NAME` } },
    { name: 'DB_USER', value: `${module}_user` },
    { name: 'DB_PASSWORD', valueFrom: { secretKeyRef: `${p}_PASSWORD` } },
  ];
}

/**
 * A datastore URL that carries a credential, assembled by the kubelet.
 *
 * `$(VAR)` in an env value is expanded against the variables already in the
 * container's environment, which includes everything `envFrom` brought in — so
 * the password reaches the URL without the manifest ever holding it. Emitted
 * only for a service whose registry entry declares the dependency: unlike
 * Compose there is no `env_file` here handing a localhost default to everyone
 * else, so an address nobody needs is just noise.
 */
export function datastoreUriEnv(s) {
  const deps = s.dependsOn ?? [];
  const out = [];
  if (deps.includes('mongodb'))
    out.push({
      name: 'MONGO_URI',
      value:
        'mongodb://$(MONGO_ROOT_USER):$(MONGO_ROOT_PASSWORD)@' +
        `${INFRA_ENDPOINT.mongodb.host}:27017/$(MONGO_DB_NAME)?authSource=admin`,
    });
  if (deps.includes('elasticsearch'))
    out.push({
      name: 'ELASTICSEARCH_NODE',
      // The credential stays in the URL: elasticsearch-endpoint.ts parses it
      // into an Authorization header, because fetch() rejects a URL carrying
      // credentials.
      value: `http://elastic:$(ELASTIC_PASSWORD)@${INFRA_ENDPOINT.elasticsearch.host}:9200`,
    });
  return out;
}

/** Pod identity, for the log lines every service writes at boot. */
const POD_METADATA_ENV = [
  { name: 'POD_NAME', valueFrom: { fieldRef: 'metadata.name' } },
  { name: 'POD_NAMESPACE', valueFrom: { fieldRef: 'metadata.namespace' } },
  { name: 'POD_IP', valueFrom: { fieldRef: 'status.podIP' } },
];

export function containerEnv(s, reg) {
  if (WEB_KINDS.includes(s.kind)) {
    const env = [
      ...POD_METADATA_ENV,
      // Server-side fetches and the `/api/*` rewrites in next.config.mjs go
      // straight to the gateway Service. The browser uses the build-time
      // NEXT_PUBLIC_API_URL baked into the image.
      { name: 'API_URL', value: `http://${SVC('api-gateway')}:3001/api/v1` },
      { name: 'API_GATEWAY_ORIGIN', value: `http://${SVC('api-gateway')}:3001` },
    ];
    if (s.kind === 'web-shell')
      for (const z of reg.services.filter((x) => x.kind === 'web-zone'))
        env.push({
          name: `${stem(z.name)}_ZONE_ORIGIN`,
          value: `http://${SVC(z.name)}:${z.ports.http}`,
        });
    return env;
  }

  const env = [...POD_METADATA_ENV];
  // Where this service's own HTTP listener accepts. marketplace-service reads
  // MARKETPLACE_HTTP_HOST and defaults to loopback, which a probe arriving on
  // the pod IP cannot reach; emitted for every Nest service under its own stem
  // so the next one to adopt the pattern is correct by default.
  env.push({ name: `${stem(s.name)}_HTTP_HOST`, value: '0.0.0.0' });
  if (s.kafka) env.push({ name: 'KAFKA_GROUP_ID', value: s.kafka.groupId });
  env.push(...credentialEnv(s));
  env.push(...datastoreUriEnv(s));
  return env;
}

function envBlock(env) {
  const lines = ['env:'];
  for (const e of env) {
    lines.push(`  - name: ${e.name}`);
    if (e.valueFrom?.fieldRef) {
      lines.push('    valueFrom:', '      fieldRef:', `        fieldPath: ${e.valueFrom.fieldRef}`);
    } else if (e.valueFrom?.secretKeyRef) {
      lines.push(
        '    valueFrom:',
        '      secretKeyRef:',
        '        name: kartseek-secrets',
        `        key: ${e.valueFrom.secretKeyRef}`,
      );
    } else if (e.valueFrom?.configMapKeyRef) {
      lines.push(
        '    valueFrom:',
        '      configMapKeyRef:',
        '        name: kartseek-config',
        `        key: ${e.valueFrom.configMapKeyRef}`,
      );
    } else {
      lines.push(`    value: ${q(e.value)}`);
    }
  }
  return lines;
}

/**
 * The three probes.
 *
 * `startupProbe` holds liveness and readiness off until the process answers at
 * all — 30 × 10s, comfortably past the 60 s a cold Nest boot with a TypeORM
 * connection and a Kafka client can take — so neither carries an
 * `initialDelaySeconds`: with a startup probe present, that delay is dead
 * configuration that only makes a healthy pod look slow.
 */
function probeBlocks(s) {
  const { live, ready } = probePaths(s);
  const loopback = LOOPBACK_HTTP.has(s.name);
  const target = (path) =>
    loopback
      ? ['tcpSocket:', `  port: ${s.ports.tcp ?? s.ports.http}`]
      : ['httpGet:', `  path: ${path}`, '  port: http'];

  const lines = [];
  if (loopback)
    lines.push(
      '# This service binds its HTTP listener to 127.0.0.1 (see LOOPBACK_HTTP in',
      '# scripts/registry/k8s.mjs), which the kubelet cannot reach — so all three',
      '# probes fall back to the TCP transport, which does bind 0.0.0.0. A port',
      '# being open is a weaker claim than /health/ready; it is what is available.',
    );
  lines.push(
    'livenessProbe:',
    ...indent(2, target(live)),
    '  periodSeconds: 15',
    '  timeoutSeconds: 5',
    '  failureThreshold: 3',
    'readinessProbe:',
    ...indent(2, target(ready)),
    '  periodSeconds: 10',
    '  timeoutSeconds: 3',
    '  failureThreshold: 3',
    'startupProbe:',
    ...indent(2, target(live)),
    '  periodSeconds: 10',
    '  timeoutSeconds: 3',
    // 30 × 10s = 300s. The ruling is ≥ 60s; a cold boot behind an init container
    // that has just watched Postgres come up needs more than the minimum.
    '  failureThreshold: 30',
  );
  return lines;
}

export function renderService(s) {
  return [
    '---',
    'apiVersion: v1',
    'kind: Service',
    'metadata:',
    `  name: ${s.name}`,
    `  namespace: ${NAMESPACE}`,
    '  labels:',
    `    app: ${s.name}`,
    `    tier: ${tierOf(s)}`,
    'spec:',
    '  type: ClusterIP',
    '  selector:',
    `    app: ${s.name}`,
    '  ports:',
    ...indent(4, servicePorts(s)),
  ].join('\n');
}

/**
 * `tier` is not decoration: namespace.yaml's NetworkPolicies select on it.
 * `allow-microservice-mesh` opens a Nest pod to the gateway and its peers, and
 * `allow-web-tier` opens a Next pod to the ingress controller and to the shell.
 */
export const tierOf = (s) => (WEB_KINDS.includes(s.kind) ? 'web' : 'microservice');

export function renderDeployment(s, reg) {
  const r = resourcesFor(s);
  const uid = runAsUserFor(s);
  const containerPorts = Object.entries(s.ports).flatMap(([kind, port]) => [
    `- name: ${kind}`,
    `  containerPort: ${port}`,
    '  protocol: TCP',
  ]);
  const body = [
    '---',
    'apiVersion: apps/v1',
    'kind: Deployment',
    'metadata:',
    `  name: ${s.name}`,
    `  namespace: ${NAMESPACE}`,
    '  labels:',
    `    app: ${s.name}`,
    `    tier: ${tierOf(s)}`,
    'spec:',
    '  replicas: 2',
    '  strategy:',
    '    type: RollingUpdate',
    '    rollingUpdate:',
    '      maxSurge: 1',
    '      maxUnavailable: 0',
    '  selector:',
    '    matchLabels:',
    `      app: ${s.name}`,
    '  template:',
    '    metadata:',
    '      labels:',
    `        app: ${s.name}`,
    `        tier: ${tierOf(s)}`,
    '    spec:',
    ...indent(6, [
      ...(WEB_KINDS.includes(s.kind) ? [] : ['serviceAccountName: microservice']),
      'imagePullSecrets:',
      '  - name: regcred',
      'securityContext:',
      '  runAsNonRoot: true',
      `  runAsUser: ${uid}`,
      `  fsGroup: ${uid}`,
      ...initContainers(s),
      'containers:',
    ]),
    ...indent(8, [
      `- name: ${s.name}`,
      `  image: ${s.image}:\${KARTSEEK_TAG}`,
      '  imagePullPolicy: IfNotPresent',
      '  envFrom:',
      '    - configMapRef:',
      '        name: kartseek-config',
      // A Next server needs none of the platform's credentials — NEXT_PUBLIC_*
      // are inlined at build time and everything else it reads is below — and a
      // Secret it never receives is a Secret its image cannot leak.
      ...(WEB_KINDS.includes(s.kind) ? [] : ['    - secretRef:', '        name: kartseek-secrets']),
      ...indent(2, envBlock(containerEnv(s, reg))),
      '  ports:',
      ...indent(4, containerPorts),
      ...indent(2, probeBlocks(s)),
      '  resources:',
      '    requests:',
      `      cpu: ${q(r.cpu)}`,
      `      memory: ${q(r.memory)}`,
      '    limits:',
      `      cpu: ${q(r.cpuLimit)}`,
      `      memory: ${q(r.memoryLimit)}`,
      '  securityContext:',
      '    allowPrivilegeEscalation: false',
      '    runAsNonRoot: true',
      `    runAsUser: ${uid}`,
      '    capabilities:',
      '      drop:',
      '        - ALL',
    ]),
    ...indent(6, [
      'affinity:',
      '  podAntiAffinity:',
      '    preferredDuringSchedulingIgnoredDuringExecution:',
      '      - weight: 100',
      '        podAffinityTerm:',
      '          labelSelector:',
      '            matchExpressions:',
      '              - key: app',
      '                operator: In',
      '                values:',
      `                  - ${s.name}`,
      '          topologyKey: kubernetes.io/hostname',
      'terminationGracePeriodSeconds: 30',
    ]),
  ];
  return body.join('\n');
}

export function renderMicroservices(reg) {
  const entries = reg.services.filter((s) => s.kind !== 'gateway');
  const body = entries.map((s) => `${renderService(s)}\n${renderDeployment(s, reg)}`).join('\n');
  return `${HEADER}${body}\n`;
}
