/** KARTSEEK — Doctor Appointment Route Constants */
export const DOCTOR_ROUTES = {
  HOME:              '/doctor',
  SEARCH:            '/doctor/search',
  PROFILE:           (slug: string) => `/doctor/profile/${slug}`,
  BOOK:              (doctorId: string) => `/doctor/book/${doctorId}`,
  MY_APPOINTMENTS:   '/doctor/my-appointments',
  MY_DOCTORS:        '/doctor/my-doctors',
  HOSPITAL:          (id: string) => `/doctor/hospital/${id}`,
  CLINIC:            (id: string) => `/doctor/clinic/${id}`,
  REVIEW:            (appointmentId: string) => `/doctor/review/${appointmentId}`,
  MEDICAL_RECORDS:   '/doctor/medical-records',
  WELLNESS_REWARDS:  '/doctor/wellness-rewards',
  PRESCRIPTIONS:     '/doctor/prescriptions',
  PRESCRIPTION_DETAIL: (id: string) => `/doctor/prescriptions/${id}`,
  FAMILY_MEMBERS:    '/doctor/family-members',

  // ── Seller Portal (Doctor's Portal) ────────────────────────────────────
  SELLER_LOGIN:          '/seller/doctor/login',
  SELLER_REGISTER:       '/seller/doctor/register',
  SELLER_DASHBOARD:      '/seller/doctor/dashboard',
  SELLER_PROFILE:        '/seller/doctor/profile',
  SELLER_MY_DOCTORS:     '/seller/doctor/my-doctors',
  SELLER_MY_SPECIALTIES: '/seller/doctor/my-specialties',
  SELLER_APPOINTMENTS:   '/seller/doctor/appointments',
  SELLER_QUEUE:          '/seller/doctor/queue',
  SELLER_PRESCRIPTIONS:  '/seller/doctor/prescriptions',
  SELLER_WRITE_RX:       '/seller/doctor/prescriptions/write',
  SELLER_AVAILABILITY:   '/seller/doctor/availability',
  SELLER_PATIENTS:       '/seller/doctor/patients',
  SELLER_REVIEWS:        '/seller/doctor/reviews',
  SELLER_DOCUMENTS:      '/seller/doctor/documents',
  SELLER_EARNINGS:       '/seller/doctor/earnings',
  SELLER_SETTINGS:       '/seller/doctor/settings',
} as const;
