/**
 * KARTSEEK — TCP Message Patterns for All Modules
 *
 * These constants mirror the @MessagePattern({ cmd }) values registered in each
 * microservice controller. The gateway uses these via ClientProxy.send().
 */

// ── Grocery ─────────────────────────────────────────────────────────────────
export const GROCERY_PATTERNS = {
  GET_STORES:                 'get_grocery_stores',
  GET_STORE:                  'get_grocery_store',
  GET_CATEGORIES:             'get_grocery_categories',
  GET_CATEGORY:               'get_grocery_category',
  GET_STORE_CATEGORIES:       'get_store_categories',
  GET_PRODUCTS:               'get_grocery_products',
  GET_PRODUCT:                'get_grocery_product',
  SEARCH_PRODUCTS:            'search_grocery_products',
  CREATE_ORDER:               'create_grocery_order',
  GET_ORDER:                  'get_grocery_order',
  GET_ORDER_STATUS:           'get_grocery_order_status',
  GET_CUSTOMER_ORDERS:        'get_customer_grocery_orders',
  UPDATE_ORDER_STATUS:        'update_grocery_order_status',
  GET_STORE_ORDERS:           'get_store_grocery_orders',
  CREATE_PRODUCT:             'create_grocery_product',
  UPDATE_PRODUCT:             'update_grocery_product',
  DELETE_PRODUCT:             'delete_grocery_product',
  GET_ANALYTICS:              'get_grocery_store_analytics',
  UPDATE_STORE_SETTINGS:      'update_grocery_store_settings',
  GET_LOW_STOCK:              'get_grocery_low_stock',
  BULK_IMPORT_PRODUCTS:       'bulk_import_grocery_products',
  CREATE_CATEGORY:            'create_grocery_category',
  UPDATE_CATEGORY:            'update_grocery_category',
  INVALIDATE_CACHE:           'invalidate_grocery_cache',
  GET_PROMOTIONS:             'get_grocery_store_promotions',
  TOGGLE_PROMOTION:           'toggle_grocery_promotion',
  CREATE_FLASH_DEAL:          'create_flash_deal',
  SUBMIT_FLASH_DEAL:          'submit_flash_deal',
  APPROVE_FLASH_DEAL:         'approve_flash_deal',
  REJECT_FLASH_DEAL:          'reject_flash_deal',
  GET_STORE_FLASH_DEALS:      'get_store_flash_deals',
  PAUSE_FLASH_DEAL:           'pause_flash_deal',
  RESUME_FLASH_DEAL:          'resume_flash_deal',
  SUBMIT_REVIEW:              'submit_grocery_review',
  GET_PRODUCT_REVIEWS:        'get_product_reviews',
  GET_WISHLIST:               'get_grocery_wishlist',
  ADD_TO_WISHLIST:             'add_to_grocery_wishlist',
  REMOVE_FROM_WISHLIST:        'remove_from_grocery_wishlist',
  REORDER:                    'reorder_grocery',
  EXPORT_PRODUCTS:            'export_grocery_products',
  UPDATE_TRANSLATION:         'update_product_translation',
  GET_TRANSLATED:             'get_product_translated',
} as const;

// ── Restaurant ──────────────────────────────────────────────────────────────
export const RESTAURANT_PATTERNS = {
  GET_BY_ID:                  'get_restaurant_by_id',
  GET_MENU:                   'get_restaurant_menu',
  GET_NEARBY:                 'get_nearby_restaurants',
  PLACE_ORDER:                'place_restaurant_order',
  GET_ANALYTICS:              'get_restaurant_analytics',
} as const;

// ── Pharmacy ────────────────────────────────────────────────────────────────
export const PHARMACY_PATTERNS = {
  HEALTH:                     'pharmacy_health',
  HOME:                       'pharmacy_home',
  LIST_STORES:                'list_pharmacy_stores',
  GET_STORE:                  'get_pharmacy_store',
  GET_STORE_BY_SLUG:          'get_pharmacy_store_by_slug',
  SEARCH_STORES:              'search_pharmacy_stores',
  GET_CATEGORIES:             'get_pharmacy_categories',
  GET_CATEGORY:               'get_pharmacy_category',
  GET_MEDICINES:              'get_pharmacy_medicines',
  GET_MEDICINE:               'get_pharmacy_medicine',
  SEARCH_MEDICINES:           'search_medicines',
  LOOKUP_BARCODE:             'lookup_by_barcode',
  UPLOAD_PRESCRIPTION:        'upload_prescription',
  GET_PRESCRIPTIONS:          'get_customer_prescriptions',
  VERIFY_PRESCRIPTION:        'verify_prescription',
  GET_PENDING_PRESCRIPTIONS:  'get_pending_prescriptions',
  PLACE_ORDER:                'place_pharmacy_order',
  GET_ORDER:                  'get_pharmacy_order',
  GET_CUSTOMER_ORDERS:        'get_customer_pharmacy_orders',
  GET_REVIEWS:                'get_pharmacy_reviews',
  SUBMIT_REVIEW:              'submit_pharmacy_review',
  GET_PROMOTIONS:             'get_pharmacy_promotions',
  GET_DASHBOARD:              'get_pharmacy_dashboard',
  GET_SELLER_ORDERS:          'get_pharmacy_seller_orders',
  UPDATE_ORDER_STATUS:        'update_pharmacy_order_status',
  ADD_MEDICINE:               'add_pharmacy_medicine',
  UPDATE_MEDICINE:            'update_pharmacy_medicine',
  DELETE_MEDICINE:            'delete_pharmacy_medicine',
  GET_INVENTORY:              'get_pharmacy_inventory',
  UPDATE_STOCK:               'update_pharmacy_stock',
  GET_STAFF:                  'get_pharmacy_staff',
  ADD_STAFF:                  'add_pharmacy_staff',
  UPDATE_STAFF:               'update_pharmacy_staff',
  REMOVE_STAFF:               'remove_pharmacy_staff',
  GET_PAYOUTS:                'get_pharmacy_payouts',
  GET_EARNINGS:               'get_pharmacy_earnings',
  CREATE_PROMOTION:           'create_pharmacy_promotion',
  UPDATE_PROMOTION:           'update_pharmacy_promotion',
  DELETE_PROMOTION:           'delete_pharmacy_promotion',
  GET_ANALYTICS:              'get_pharmacy_analytics',
  ADMIN_APPROVE_STORE:        'approve_pharmacy_store',
  ADMIN_SUSPEND_STORE:        'suspend_pharmacy_store',
  ADMIN_LIST_STORES:          'admin_list_pharmacy_stores',
  SET_COMMISSION:             'set_pharmacy_commission',
  GET_BY_FRANCHISE:           'get_pharmacy_stores_by_franchise',
} as const;

// ── Taxi ────────────────────────────────────────────────────────────────────
export const TAXI_PATTERNS = {
  ESTIMATE_FARE:              'estimate_taxi_fare',
  REQUEST_RIDE:               'request_ride',
  DRIVER_ACCEPT:              'driver_accept_ride',
  DRIVER_REJECT:              'driver_reject_ride',
  DRIVER_GO_ONLINE:           'driver_go_online',
  DRIVER_GO_OFFLINE:          'driver_go_offline',
} as const;

// ── Hotel ───────────────────────────────────────────────────────────────────
export const HOTEL_PATTERNS = {
  HEALTH:                     'hotel_health',
  SEARCH:                     'search_hotels',
  GET_HOTEL:                  'get_hotel',
  CREATE_BOOKING:             'create_hotel_booking',
  GET_AVAILABILITY:           'get_room_availability',
  GET_BOOKING:                'get_hotel_booking',
  GET_USER_BOOKINGS:          'get_user_bookings',
  CANCEL_BOOKING:             'cancel_hotel_booking',
  MODIFY_BOOKING:             'modify_hotel_booking',
  SUBMIT_REVIEW:              'submit_hotel_review',
  GET_REVIEWS:                'get_hotel_reviews',
  // Owner
  REGISTER_OWNER:             'register_hotel_owner',
  CREATE_HOTEL:               'create_hotel',
  UPDATE_HOTEL:               'update_hotel',
  OWNER_DASHBOARD:            'get_owner_dashboard',
  OWNER_BOOKINGS:             'get_owner_bookings',
  UPDATE_ROOM_PRICING:        'update_room_pricing',
  BULK_UPDATE_PRICING:        'bulk_update_pricing',
  MARK_NO_SHOW:               'mark_no_show',
  OWNER_PAYOUTS:              'get_owner_payouts',
  OWNER_REVIEWS:              'get_owner_reviews',
  REPLY_REVIEW:               'reply_to_review',
  // Admin
  ADMIN_STATS:                'admin_hotel_stats',
  ADMIN_LIST:                 'admin_list_hotels',
  ADMIN_APPROVE:              'admin_approve_hotel',
  ADMIN_SUSPEND:              'admin_suspend_hotel',
  ADMIN_FRAUD:                'admin_fraud_flags',
  ADMIN_COMPLIANCE:           'admin_compliance',
  ADMIN_REVENUE:              'admin_revenue',
  ADMIN_ONBOARDING:           'admin_onboarding',
} as const;

// ── Doctor ──────────────────────────────────────────────────────────────────
export const DOCTOR_PATTERNS = {
  GET_SPECIALTIES:            'get_specialties',
  GET_HOSPITALS:              'get_hospitals',
  GET_HOSPITAL:               'get_hospital',
  GET_HOSPITAL_DOCTORS:       'get_hospital_doctors',
  UPDATE_HOSPITAL_STATUS:     'update_hospital_status',
  GET_CLINICS:                'get_clinics',
  GET_CLINIC:                 'get_clinic',
  UPDATE_CLINIC_STATUS:       'update_clinic_status',
  GET_DOCTORS:                'get_doctors',
  GET_DOCTOR:                 'get_doctor',
  GET_DOCTOR_SLOTS:           'get_doctor_slots',
  UPDATE_DOCTOR_STATUS:       'update_doctor_status',
  BOOK_APPOINTMENT:           'book_appointment',
  GET_MY_APPOINTMENTS:        'get_my_appointments',
  GET_PROVIDER_APPOINTMENTS:  'get_provider_appointments',
  UPDATE_APPOINTMENT_STATUS:  'update_appointment_status',
  RESCHEDULE_APPOINTMENT:     'reschedule_appointment',
  GET_ALL_APPOINTMENTS:       'get_all_appointments',
  GET_REVIEWS:                'get_reviews',
  ADVANCE_TOKEN:              'advance_token',
  GET_QUEUE_STATUS:           'get_queue_status',
  CHECK_IN_PATIENT:           'check_in_patient',
  START_CONSULTATION:         'start_consultation',
  END_CONSULTATION:           'end_consultation',
  CREATE_PRESCRIPTION:        'create_prescription',
  ISSUE_PRESCRIPTION:         'issue_prescription',
  GET_PRESCRIPTION:           'get_prescription',
  GET_PRESCRIPTIONS_BY_PATIENT: 'get_prescriptions_by_patient',
  GET_PRESCRIPTIONS_BY_DOCTOR: 'get_prescriptions_by_doctor',
  LINK_PRESCRIPTION_PHARMACY: 'link_prescription_pharmacy',
  GET_FAMILY_MEMBERS:         'get_family_members',
  ADD_FAMILY_MEMBER:          'add_family_member',
  UPDATE_FAMILY_MEMBER:       'update_family_member',
  DELETE_FAMILY_MEMBER:       'delete_family_member',
  SUBMIT_INTAKE_FORM:         'submit_intake_form',
  GET_INTAKE_FORM:            'get_intake_form',
} as const;

// ── Wallet ──────────────────────────────────────────────────────────────────
export const WALLET_PATTERNS = {
  GET_WALLET:                 'get_wallet',
  DEBIT:                      'wallet_debit',
  CREDIT:                     'wallet_credit',
  FREEZE:                     'wallet_freeze',
  UNFREEZE:                   'wallet_unfreeze',
  GET_TRANSACTIONS:           'wallet_get_transactions',
  SEARCH_TRANSACTIONS:        'wallet_search_transactions',
} as const;

// ── Loyalty ─────────────────────────────────────────────────────────────────
export const LOYALTY_PATTERNS = {
  GET_POINTS:                 'get_loyalty_points',
  AWARD_POINTS:               'award_loyalty_points',
  REVERSE_POINTS:             'reverse_loyalty_points',
  PREVIEW_POINTS:             'preview_loyalty_points',
  ADJUST_POINTS:              'adjust_loyalty_points',
  GET_FOR_ORDER:              'get_loyalty_for_order',
} as const;

// ── Franchise ───────────────────────────────────────────────────────────────
export const FRANCHISE_PATTERNS = {
  HEALTH:                     'franchise.health',
  REGISTER:                   'franchise.register',
  GET_DASHBOARD:              'franchise.get_dashboard',
  GET_STORES:                 'franchise.get_stores',
  GET_PERFORMANCE:            'franchise.get_performance',
  SUBMIT_COMPLIANCE:          'franchise.submit_compliance',
  // Sub-module KPIs
  MARKETPLACE_GET_KPIS:       'franchise.marketplace.get_kpis',
  MARKETPLACE_GET_SELLERS:    'franchise.marketplace.get_sellers',
  GROCERY_GET_KPIS:           'franchise.grocery.get_kpis',
  GROCERY_GET_STORES:         'franchise.grocery.get_stores',
  GROCERY_GET_ORDERS:         'franchise.grocery.get_orders',
  RESTAURANT_GET_KPIS:        'franchise.restaurant.get_kpis',
  RESTAURANT_GET_RESTAURANTS: 'franchise.restaurant.get_restaurants',
  PHARMACY_GET_KPIS:          'franchise.pharmacy.get_kpis',
  PHARMACY_GET_STORES:        'franchise.pharmacy.get_stores',
  DOCTOR_GET_KPIS:            'franchise.doctor.get_kpis',
  DOCTOR_GET_CLINICS:         'franchise.doctor.get_clinics',
  TAXI_GET_KPIS:              'franchise.taxi.get_kpis',
  TAXI_GET_DRIVERS:           'franchise.taxi.get_drivers',
  HOTEL_GET_KPIS:             'franchise.hotel.get_kpis',
  HOTEL_GET_HOTELS:           'franchise.hotel.get_hotels',
} as const;
